### ISSUE TITLE
Notifications in menu bar

### ISSUE THREAD

**Issue by bryangarza** [rsms/fb-mac-messenger#100]
It would be neat to have a count of unread messages in the menu bar. When my computer is muted I often don't notice new messages.

I wonder if there's an easy way to implement this.

Thoughts?

**Comment by Sheraff** [comment]
I know of one github project that allows for easy menubar tinkering: https://github.com/maxogden/menubar

**Comment by rsms** [comment]
The app icon is currently badged. I'm reluctant to introduce a status item into the system status bar as this app doesn't _really_ need it.

And FTR, it's trivial to implement w/o any libraries or frameworks. Just a few lines of code (see `-NSStatusBar statusItemWithLength`)
