### ISSUE TITLE
Search bar missing, leaves blank space

### ISSUE THREAD

**Issue by gabriellewee** [rsms/fb-mac-messenger#101]
![screen shot 2015-04-21 at 11 29 03 pm](https://cloud.githubusercontent.com/assets/636958/7268430/44682cca-e87e-11e4-8520-bd5462c379d5.png)

I know the settings icon was already referenced in another issue. I tried deleting and reinstalling - the search bar showed up the first time I opened up the reinstalled version, then disappeared the next few times I opened the app.

**Comment by dapetcu21** [comment]
Fixed in #103
