### ISSUE TITLE
Settings icon 

### ISSUE THREAD

**Issue by Lotuashvili** [rsms/fb-mac-messenger#104]
Settings icon was hidden, but now it is shown and search bar is hidden... cmd + f doesn't show search bar too..

![screen shot 2015-04-22 at 8 26 56](https://cloud.githubusercontent.com/assets/6238393/7279474/55f812f2-e92d-11e4-8192-cac27f1aadcb.png)

**Comment by dapetcu21** [comment]
Duplicate of #102, fixed in #103
