### ISSUE TITLE
Enable pasting images and files in message composer

### ISSUE THREAD

**Issue by blakeembrey** [rsms/fb-mac-messenger#109]
I attempted to understand some Objective-C to get this working, but no luck. Basically, Facebook used to have a feature where you can paste images and send them. Super handy. Issue is, `event.clipboardData` appears to be empty in the webview and I have no idea to let images pass through. Any help would be fantastic!

Edit: Maybe relevant PR from a related project https://github.com/danielbuechele/goofy/pull/55

**Comment by lazywei** [comment]
would love this feature to be in the App!!!

**Comment by rsms** [comment]
Interesting. Seems #120 is adding this functionality. I don't have time tonight to test it out, but if someone else can merge #120 and confirm it's working we could move a little quicker.

**Comment by rsms** [comment]
Closed by #120
