### ISSUE TITLE
App couldn't remember Check Spelling While Typing setting

### ISSUE THREAD

**Issue by zulhfreelancer** [rsms/fb-mac-messenger#114]
By default, app is checking spelling:

Edit > Spelling and Grammar > ✓ Check Spelling While Typing

I turned off the spell check, quit and reopen it. Unfortunately, the app couldn't remember the Check Spelling While Typing setting that has been turned off.

I need to do it manually everytime I quit and reopen the app.

**Comment by rsms** [comment]
Would accept a PR for this.
Not sure how to make this happen.

**Comment by sethk** [comment]
I'd like to look into this, because I think I also broke the spellcheck menu when I disabled the context menus.
