### ISSUE TITLE
Alternative app icon

### ISSUE THREAD

**Issue by vaner-org** [rsms/fb-mac-messenger#116]
Since this app basically intends just to be a desktop version of messenger.com, with no added caveats like a unique name, I feel that it should also share Messenger's default icon, as opposed to the Messenger logo within a grey circle.

I made one in Sketch, and altered it's proportions a bit so that it looks good alongside Messages. Files with .icns extension can't be directly posted in the comment so here's a download link:
https://www.dropbox.com/s/weov2vyde6h021z/Messenger.icns?dl=0

**Comment by dominik-hadl** [comment]
:+1:

**Comment by rsms** [comment]
Interesting, and nice work.
I'll leave this open and unchanged for now. Feel free to submit a PR with your new icon.

**Comment by sos4nt** [comment]
:+1: but OS X icons usually have a subtle shadow.

**Comment by craftyninja** [comment]
:+1: 
I like it!!

**Comment by rsms** [comment]
Rather use asset catalog and PNG images. I imitated the icon used at messenger.com to create a new icon, landed in f7ea99809dc57e29a0a279be00ccea2873c4b231, made with Figma so it's all vectors (https://github.com/rsms/fb-mac-messenger/blob/master/Messenger/icon.fig)

**Comment by rsms** [comment]
<img width="372" alt="screenshot 2016-02-10 09 59 49" src="https://cloud.githubusercontent.com/assets/47046/12956649/dff1227c-cfdd-11e5-9751-edbd48d14cc4.png">
