### ISSUE TITLE
Compact contact list view

### ISSUE THREAD

**Issue by oraveczandrew** [rsms/fb-mac-messenger#119]
Sometimes we don't want that the window occupy the whole screen, but we can't resize the window to lower than 640px.
I think the contact list with pics is enough to switch between contacts.

![screen shot 2015-05-11 at 06 13 54](https://cloud.githubusercontent.com/assets/3141613/7558483/b5e164ee-f7a5-11e4-82de-8519910919bb.png)

**Comment by rsms** [comment]
No. This project's goal is to put Messenger.com on the desktop, not to alter it or create a different version of it.
