### ISSUE TITLE
Title bar and full screen mode.

### ISSUE THREAD

**Issue by jondavidschober** [rsms/fb-mac-messenger#12]
I noticed that both the buttons and full screen mode with disabled intentionally. I changed it so they are on in my build, this allows me to treat messenger just like iMessages. I can have them both in full screen mode and swipe between them. Due to the similar UI, it feel natural.

**Comment by rsms** [comment]
Done (https://github.com/rsms/fb-mac-messenger/commit/cd486a698c2e7908ade158c6d398e73f91900c96) and done (https://github.com/rsms/fb-mac-messenger/commit/751810b04a72b8383f0dc97e780aef4d715d72e8).

**Comment by jondavidschober** [comment]
Awesome thanks
