### ISSUE TITLE
Buggy drag-to-upload-image

### ISSUE THREAD

**Issue by szhu** [rsms/fb-mac-messenger#124]
This is hard to reproduce because it happens every once in a while.

Dragging images into the main window should send the image. Instead, sometimes the image is sent twice and (in group chats) sometimes the group image is changed instead of the image being sent.

**Comment by rsms** [comment]
Closing until we can reproduce. Might or might not be messenger.com

**Comment by szhu** [comment]
Messenger.com does not have the drag-to-upload feature at all.
