### ISSUE TITLE
Messenger always says it's offline

### ISSUE THREAD

**Issue by egorvinogradov** [rsms/fb-mac-messenger#125]
![image](https://cloud.githubusercontent.com/assets/1618344/7920100/81d1ac38-0851-11e5-9cd9-2f75a657c821.png)

Messenger always says it's offline. Internet works though, I can open https://www.messenger.com/. It's the last 0.0.7 version. I have Mac OS 10.10.4

**Comment by rsms** [comment]
Can't reproduce.
Does this happen every time you start the app, or did it happen just once?

**Comment by rsms** [comment]
Ping @egorvinogradov

**Comment by egorvinogradov** [comment]
@rsms It was happening all the time I run the app. That time I just deleted it. Now, I reinstalled the app again and it works! But I definitely was able to open https://www.messenger.com at the same time when the app showed it was offline. Don't know what happened. Sorry about that.

**Comment by egorvinogradov** [comment]
@rsms 
I installed it on a different macbook and got the problem again. Happens all the time I launch the app.
Version 0.0.8, Mac OS 10.10.4, internet works, I can open https://www.messenger.com/

![image](https://cloud.githubusercontent.com/assets/1618344/8200242/e67ae7a4-1476-11e5-8c92-b47425cb669e.png)

Is there anything I can debug locally?

**Comment by rsms** [comment]
Does using messenger.com in Safari work for you?
Also, do this and let us know the results:

```
host -a www.messenger.com
curl -i https://www.messenger.com/
```

**Comment by egorvinogradov** [comment]
@rsms messenger.com works in safari

``` bash
➜  ~  host -a www.messenger.com
Trying "www.messenger.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65297
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.messenger.com.     IN  ANY

;; ANSWER SECTION:
www.messenger.com.  1611    IN  CNAME   star.c10r.facebook.com.

Received 68 bytes from 8.8.8.8#53 in 53 ms
➜  ~  
➜  ~  
```

---

``` bash
➜  ~  curl -i https://www.messenger.com/
HTTP/1.1 200 OK
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-Frame-Options: DENY
X-XSS-Protection: 0
X-Content-Type-Options: nosniff
Vary: Accept-Encoding
Content-Type: text/html
X-FB-Debug: Iuq0jLx/SAhpb63I17lDluK4hqInUtfDLl9MGqUp678xV3GKhGz7U8Xz4U1MERpWcq8XtfZikhz2ATPXzULwWQ==
Date: Fri, 19 Jun 2015 08:55:07 GMT
Transfer-Encoding: chunked
Connection: keep-alive

<!DOCTYPE html>
# ...
# the rest of messanger.com HTML code
# ...
```

**Comment by rsms** [comment]
Weird!
If you open Console.app and filter on Messenger, what do you see? There are hopefully a few lines like these:

```
6/20/15 06:39:43.626 Messenger[67488]: webView:didFailProvisionalLoadWithError:forFrame: error=Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo=0x6180000ee600 {NSUnderlyingError=0x618000244e00 "The network connection was lost.", NSErrorFailingURLStringKey=https://www.messenger.com/t/foo, NSErrorFailingURLKey=https://www.messenger.com/t/foo, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=57, NSLocalizedDescription=The network connection was lost.}
```

Would you mind posting any log messages that appear when you start the app and it "goes offline"? Thanks.

**Comment by rsms** [comment]
dead
