### ISSUE TITLE
There is no application set to open the URL about:blank

### ISSUE THREAD

**Issue by janant** [rsms/fb-mac-messenger#126]
When opening the app as well as when switching between conversations, 2 of the standard OS X "There is no application set to open..." menus for about:blank. I think Facebook probably did some changes in messenger.com since it was working fine just before and some of my friends are now having the same issue. I think a new update is needed to fix this.

**Comment by ubergraham** [comment]
Just started getting the same error just now as well.

**Comment by Phong2503** [comment]
same here :(, I thought it was caused by little snitch but turned out it wasn't.

**Comment by xanderlent** [comment]
A quick code search in this project seems to indicate that this may be part of "bustIframe". While the JavaScript files from Facebook have likely changed a bit, [this research file](https://github.com/rsms/fb-mac-messenger/blob/83d2769af9d2ebe9aa17cf9c42eb5f0ee5f3c296/js-env-research/EIgoMTKaddf.js#L1275) may be a good starting point.

Potential fixes might include circumventing the iframe embed prevention (probably the best solution) and/or silently absorbing/logging the about:blank links.

**Comment by szhu** [comment]
+1

**Comment by laander** [comment]
+1 same here (often multiple dialogues on an action)

**Comment by orbxball** [comment]
Yes. Got the same problem on my Mac about 2 hours ago...
Feels annoying... though I examine the code and there's no noticeable bug there I found @@
![2015-06-03 3 41 10](https://cloud.githubusercontent.com/assets/10207726/7955025/6d041f5e-0a07-11e5-8f67-6777bdf2b92d.png)

**Comment by npes87184** [comment]
the same issue

**Comment by MMaikeru** [comment]
Yup. Same problem here.

**Comment by binhuangtw** [comment]
I also got this problem.
It's really annoy

**Comment by szhu** [comment]
| Temporary workaround |
| :-- |
| Download this small app to eat up all the errors!<br>https://github.com/szhu/AboutWeb<br>(Please give me feedback on this!) |

**Comment by infilmity** [comment]
same here

**Comment by aldendaniels** [comment]
same here

**Comment by tmyrden** [comment]
+1

**Comment by chrismessina** [comment]
+1

**Comment by JeanLebrument** [comment]
+1

**Comment by m-dierker** [comment]
same error :)

**Comment by mcescalante** [comment]
+1 same error, Facebook must have been updating their application. More cat & mouse fixes :)

**Comment by StefanoF** [comment]
+1

**Comment by Lee-W** [comment]
+1

**Comment by m4grio** [comment]
+1

**Comment by gueyeb** [comment]
+1

**Comment by nvartolomei** [comment]
+1

**Comment by hoaithing** [comment]
. +1.fix this issue pls ! :(

**Comment by cyrandy** [comment]
+1

**Comment by pworker** [comment]
+1

**Comment by rlengvenis** [comment]
+1

**Comment by eexit** [comment]
+1

**Comment by eexit** [comment]
![screen shot 2015-06-04 at 2 58 05 pm](https://cloud.githubusercontent.com/assets/57098/7984501/29b76cec-0aca-11e5-87e1-913836c1680f.png)

**Comment by loonghuey** [comment]
+1

**Comment by andrewtch** [comment]
I know it is annoying for the devs, but... +1 )

**Comment by antonzoi** [comment]
+1

**Comment by comigor** [comment]
+1

**Comment by jonathanhills** [comment]
@szhu works for me! Nice hack.

**Comment by trevorcreech** [comment]
+1

**Comment by emilstahl** [comment]
+1
![messenger](https://cloud.githubusercontent.com/assets/3885790/7993456/84bb4f5a-0b06-11e5-887c-3e6dc47b4c38.png)

**Comment by queeniema** [comment]
+1

**Comment by emilstahl** [comment]
Nice hack @szhu :+1:

**Comment by susanlee** [comment]
Thanks @szhu  !

**Comment by dannykansas** [comment]
+1, but also thanking @szhu for the about:blank swallower hack. Clean little hack, and I don't see any reason why I'd need to handle `about:blank` with any other program, so as far as I'm concerned, it's a perma-fix. 

Maybe we could register fb-mac-messenger to handle `about:blank` by quietly swallowing the requests (assuming there's not a better workaround)

**Comment by dannykansas** [comment]
Woops, overlooked your commit, @emilstahl. That works great for me as well:

https://github.com/grEvenX/fb-mac-messenger/commit/3b2e64feeb6c506b67a6559d53727d03037b920c

**Comment by safareli** [comment]
same here

**Comment by szhu** [comment]
@dannykansas, I consider it a temporary hack because visiting `messenger.com` in a web browser doesn't cause the issue. This app needs to perform at least as well as `messenger.com`.

With that said grEvenX@3b2e64f should also be a temporary fix, because `messenger.com` doesn't require us to handle `about:blank` in a special way.

Also, posting [a link to my fix](#issuecomment-108284268) from above in case anyone missed it. :)

**Comment by jhkz** [comment]
Thanks @szhu, looks like it fixes the problem.

**Comment by skysteve** [comment]
+1

**Comment by shrwnsan** [comment]
+1

**Comment by Felipefrs** [comment]
@szhu 
Temporary or not, did work just fine, thanks!

**Comment by xanth** [comment]
+1 same issues
![+1 same issues](https://cloud.githubusercontent.com/assets/5460583/8017879/c371425e-0c46-11e5-9fb6-615ff89c8245.png)

**Comment by carlosfaria94** [comment]
+1

**Comment by hayyaan** [comment]
+1. Suppressing the about:blank URL in itself should be a good enough solution for this without resorting to an external app to handle about: links

**Comment by mikechouto** [comment]
Just overload grEvenX@3b2e64f solution for now. You won't need an external app with this temporary fix.

**Comment by Lotuashvili** [comment]
Same here :( 

![screen shot 2015-06-07 at 13 53 37](https://cloud.githubusercontent.com/assets/6238393/8023420/c66a2a1c-0d1c-11e5-87e3-48b48db31c51.png)

**Comment by rsms** [comment]
Sorry for the delay. I was on a remote island on vacation. Remedy issued and [new release has been published](http://fbmacmessenger.rsms.me/) — messenger.com seems to employ some kind of iframe hack where the iframes are requesting to open "about:blank". [The fix](https://github.com/rsms/fb-mac-messenger/commit/d640fa4b728ab130a8414a6261a1eb24217c84c6) simply ignores any URI with the "about" scheme.

**Comment by nzjoel** [comment]
Solved! Thanks @rsms!
