### ISSUE TITLE
Right-click context menu doesn't work

### ISSUE THREAD

**Issue by palkoc** [rsms/fb-mac-messenger#128]
It's impossible to delete a message/picture/object from the chat. It was working previously.
![cant_remove_object](https://cloud.githubusercontent.com/assets/6809559/8015450/d8a5af66-0bd8-11e5-824f-c7cd00fee412.jpg)
The web inspector pops up instead. is this only my problem?
Thanks.
Palkoc

**Comment by rsms** [comment]
No idea how to fix this. PR would be helpful
