### ISSUE TITLE
Trying to open other applications

### ISSUE THREAD

**Issue by gearanfool** [rsms/fb-mac-messenger#129]
Running OS 10.10.3

Each time I click on one of my chats, two windows pop up asking me to select an app to open the URL about:blank. It also happens when I restart the app but it opens 3 windows then.

![screen shot 2015-06-07 at 10 05 53](https://cloud.githubusercontent.com/assets/12786552/8025071/ed0c4e1c-0cfd-11e5-830e-71fde700670c.png)

**Comment by aimed** [comment]
this is a duplicate, same as #126

**Comment by Lotuashvili** [comment]
@gearanfool Offtopic, but can you post your wallpaper link in HD?

**Comment by gearanfool** [comment]
@Lotuashvili Its one of the default mac wallpapers so if you look in your preferences it should be there. If you can't find it then I found the image here: http://i.imgur.com/Y370T.jpg

**Comment by Lotuashvili** [comment]
@gearanfool It's not in my preferences. Thank you very much!
