### ISSUE TITLE
Warning message "There is no application set to open the URL about:blank."

### ISSUE THREAD

**Issue by nzjoel** [rsms/fb-mac-messenger#130]
Every time I click on a conversation I get a warning message that reads "There is no application set to open the URL about:blank. Search the App Store for an application that can open this document, or choose an existing application on your computer."

This is the same kind of message id get if I was trying to open a file that didnt have an app to open it. I am just trying to click a new conversation, i'm not opening a file. It doesnt matter who's conversation I click on.

I have tried uninstalling the app, restarting the app, and logging out then in to the app with no success. 

I get 2 of these messages every time I click a conversation and 3 on loading the app the first time.

See the warning message here:
![screen shot 2015-06-07 at 22 58 53](https://cloud.githubusercontent.com/assets/1848200/8026323/305fb724-0d69-11e5-806c-70d637e91357.png)

**Comment by rsms** [comment]
dupe #126
