### ISSUE TITLE
Settings dialog deformatted

### ISSUE THREAD

**Issue by m99coder** [rsms/fb-mac-messenger#131]
Notification part of settings is deformatted. The label is moved down and the current state of notification enabled or disabled is overlapping with next part.

![bildschirmfoto 2015-06-08 um 14 00 22](https://cloud.githubusercontent.com/assets/3276992/8034356/26041774-0de7-11e5-8f1c-aeed8d25db1c.png)

**Comment by rsms** [comment]
I assume this happens after reloading the app (Messenger > Reload app)?
It's an issue with messenger.com, not this app AFAIK.

**Comment by m99coder** [comment]
Okay. Thanks anyway. For me this occurs not only after reloading the app.
