### ISSUE TITLE
Notifications not appear if app is one on another desktop

### ISSUE THREAD

**Issue by nvartolomei** [rsms/fb-mac-messenger#133]
Hello,

Here is a little issue that bothers me from day to day. Usually i have chat apps like this open on a different desktop, like this 
![screen shot 2015-06-08 at 23 27 49](https://cloud.githubusercontent.com/assets/543193/8044536/1016695e-0e36-11e5-8747-d4cc2c1f9b38.png)

However when I'm working on another desktop I don't see notifications from Messenger app, I can only hear them, also there is no red indicator on the app icon.

I guess this is because app thinks it is opened and active, but it isn't because it is on another desktop, haven't dig the code.

**Comment by coderanger** [comment]
To narrow this down, it seems to work fine if another app is on top on the other desktop. Looks like it just doesn't recognize that being on an inactive desktop should make it act like it is in the background.

**Comment by robco** [comment]
WORKAROUND: Focus some another conversation which you are pretty sure you will not get any message from. Then you will get notifications.

**Comment by nvartolomei** [comment]
I'm too lazy to do this every time.

On Thursday, July 16, 2015, Robert notifications@github.com wrote:

> WORKAROUND: Focus some another conversation which you are pretty sure you
> will not get any message from. Then you will get notifications.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rsms/fb-mac-messenger/issues/133#issuecomment-121928345
> .

## 

Nicolae Vartolomei, http://nvartolomei.com/

**Comment by rsms** [comment]
This seems to be an issue with when the webview reports "focus" and "blur" events to the document.

**Comment by jllodra** [comment]
+1
It's a pity since I cannot get notifications while on other desktops, so I constantly miss messages.
Is there any chance to get this fixed? Thanks for your work.

**Comment by nzjoel** [comment]
+1
I was having this issue too and didn't realise it was due to not moving the focus off the app/conversation each time. 

I keep missing messages because I don't see the red notification badge or the notification at all!

**Comment by rsms** [comment]
This is a behaviour of messenger.com and almost impossible for us to fix, as the logic deciding when to issue a desktop notification is fairly complicated and changes often. Essentially messenger.com uses focus/blur events and window focus state to determine if you are using the app or not. We might be able to emulate/create such events and somehow set the state of the window's focus, when the app's window is in a space which is not the currently active state.

Happy to accept a well-documented patch/PR for this :)
