### ISSUE TITLE
"There is no application set to open the URL about:blank."

### ISSUE THREAD

**Issue by jedmund** [rsms/fb-mac-messenger#135]
Whenever I open the app, or switch conversations, I get two system messages that are really fun:
![image](https://cloud.githubusercontent.com/assets/383021/8066216/2d3595c2-0e9b-11e5-9efd-3e9a77025cff.png)

I have no clue what could be wrong, to be honest!

**Comment by rsms** [comment]
Messenger > Check for updates...

Fixed by https://github.com/rsms/fb-mac-messenger/commit/d640fa4b728ab130a8414a6261a1eb24217c84c6

**Comment by jedmund** [comment]
Thanks!
