### ISSUE TITLE
`Type a message...` input buggy

### ISSUE THREAD

**Issue by gabrielmaldi** [rsms/fb-mac-messenger#137]
- Even though you can (sort of, see next bullet) type in it, clicking on it appears to do nothing.
- Most of the time you need to switch to another app and then come back to see the text you wrote rendered.
- The caret is never shown.

`Version 0.0.8.2015-06-09T23:11:23Z` (7f9bb2ca00f85676d92903c4725430110f298edc)
`OS X 10.10.3`

**Comment by loonghuey** [comment]
This problem seems inherent in messenger.com

Try opening messenger.com in your browser and see that the problem persists.

**Comment by infilmity** [comment]
Safari fail, Firefox & Chrome OK (all are latest version)

**Comment by gabrielmaldi** [comment]
You are both right; [messenger.com](messenger.com) in Safari behaves exactly the same (faulty) way while in Chrome it works fine.

**Comment by LucasAdam** [comment]
Same issue. Messenger.com is working fine in Chrome indeed

**Comment by hoaithing** [comment]
Same issue. :(

**Comment by palkoc** [comment]
+1

**Comment by mcescalante** [comment]
+1, just started noticing this behavior in the last hour. Only getting the bug in Safari

**Comment by rsms** [comment]
Just to be clear, typing works but the pointer cursor is not the "text input beam", correct?

**Comment by mcescalante** [comment]
Right @rsms - I'm also not able to actually use the (non existent) cursor to select and delete text. The input is also VERY slow/laggy.

Mine is still acting up after rebooting the program & reloading - I'm on 10.9. Glad to take a video and upload if you would like :)

**Comment by rsms** [comment]
@mcescalante Might be related to #96 
This seems to be an issue with messenger.com unfortunately, and all we can do is either trust the amazing people at Facebook working on Messenger moving this bug up on their priority list, or try to mitigate the issue via our code injections (i.e. through main.js)

**Comment by mcescalante** [comment]
Yeah, I would imagine that it is #96 in action here. I think that it's something the Messenger dev team will catch if they haven't already known about it, so it's probably not worth going wild with code injections to fix their issue.

I am definitely also getting the "no cursor / buggy input" in addition to the slow input, so just wanted to chime in. Thanks for your time and all of your work @rsms :smile:

**Comment by rsms** [comment]
FYI: Facebook engineers say this is a know issue and should be fixed soon.

**Comment by gabrielmaldi** [comment]
I just gave it another try and it's working a lot better now (although not perfectly).
