### ISSUE TITLE
App renders blank

### ISSUE THREAD

**Issue by oskarhane** [rsms/fb-mac-messenger#138]
Hey,

I'm sure you've noticed but I couldn't find an issue for it yet.
Since two days or something the app renders totally blank. I've tried the "Reload app from server" (what does that actually do?) and downloaded the latest update.

No luck.
Suggestions?

**Comment by rsms** [comment]
If you open up the "Console" app and filter all messages on "messenger", what do you see?

"Reload" does what the reload button on your web browser does.

**Comment by rsms** [comment]
Closing this for now. Will reopen if we can reproduce (I can't and there are no repro instructions)

**Comment by oskarhane** [comment]
Console says: `Sparkle: ===== Messenger.app =====` and that's it.  
I know at least one more person who has this problem.  

Starting/closing a few times over and over again might actually have solved it for now.  
I have no idea what's going on, but I think you can keep this closed.
