### ISSUE TITLE
Cannot sign in, getting error 'Please try again later.'

### ISSUE THREAD

**Issue by johnpc** [rsms/fb-mac-messenger#14]
When I sign in, I get the error message `Please try again later.`

I've tried uninstalling and reinstalling the app, but it just brings me back to that same screen.

![screen shot 2015-04-08 at 10 31 52 pm](https://cloud.githubusercontent.com/assets/4824042/7059437/199e2cb8-de3f-11e4-8db8-9699531c2be5.png)

**Comment by profcocktail** [comment]
It seems this issue is coming from messenger.com directly:
![capture d ecran 2015-04-08 a 22 52 51](https://cloud.githubusercontent.com/assets/9067645/7059649/4e8ef2c4-de42-11e4-97f2-d444fb528598.png)

**Comment by rsms** [comment]
messenger.com is down for maintenance. This app loads messenger.com into a webview, and so it requires messenger.com to function. 019677e9a6329958ff799e9887657e3294c1baa8 improves on the cryptic error message.
