### ISSUE TITLE
Window control buttons overlap settings icon

### ISSUE THREAD

**Issue by joshvickerson** [rsms/fb-mac-messenger#142]
The window controls (close, minimize, fullscreen) overlap the settings icon in the friends list. It's not very pretty, it also makes clicking the settings icon a little difficult.
![screen shot 2015-06-15 at 1 55 48 pm](https://cloud.githubusercontent.com/assets/2325487/8166564/867c8efe-1366-11e5-9a5b-33f8c9b70a43.png)

**Comment by ghost** [comment]
I have the same problem 
![bez nazwy](https://cloud.githubusercontent.com/assets/6787484/8201869/335bce90-14d5-11e5-84c8-33329d97055a.png)

**Comment by joseluisq** [comment]
Yes, for me too :+1:

**Comment by rsms** [comment]
And please tell me you didn't just file this issue without reloading or restarting the app..?

**Comment by cvx** [comment]
`[aria-owns="js_2"]` is now used on sticker/emoticon button…

**Comment by cvx** [comment]
We could start identifying elements by their react component name. Here's a JS snippet I made a couple weeks ago that can help: https://gist.github.com/CvX/24bbc6ba410d0a68e547

**Comment by joshvickerson** [comment]
I've restarted the app multiple times and experience this every time. As far as I can tell I'm using the latest version.

**Comment by rsms** [comment]
@CvX Oh, interesting hack. That would probably be better than the current fragile selector hacks.
