### ISSUE TITLE
Menu entry for preferences not working

### ISSUE THREAD

**Issue by silsha** [rsms/fb-mac-messenger#147]
The menu entry for preferences and the shortcut (cmd+,) are no longer working.
Also, there is a gearwheel-smybol visible behind the window close button.

![screen shot 2015-06-18 at 23 16 05](https://cloud.githubusercontent.com/assets/31850/8242494/0654e06c-1610-11e5-80df-8a08869d3398.png)

**Comment by lucasromanomr** [comment]
This is a problem that took care here locally, the problem is not getting to do a pull-request to send to analyze.

This problem is because of the language of some people, the settings are made to come up with button based on a text.

**Comment by silsha** [comment]
You are right. When I change my facebook language to english, everything works fine. Tried it in German before.

**Comment by lucasromanomr** [comment]
Wanted to contribute to the project, JAS straightened some things locally, but must learn to do pull-request or have permission to do so.

**Comment by lucasromanomr** [comment]
#148 Ready, I hit this error that occurred
