### ISSUE TITLE
Close app window with CMD+SHIFT+W

### ISSUE THREAD

**Issue by newkind** [rsms/fb-mac-messenger#15]
Would be awesome if we could use CMD+SHIFT+W to close the window app. Other keyboard shortcuts are also welcome ;)

Thanks!

**Comment by lithammer** [comment]
I thought <kbd>cmd</kbd>+<kbd>w</kbd> was the default for that? Or is that based on locale?

**Comment by newkind** [comment]
Different apps use different shortcuts ie. In some cmd+w closes the current conversation while cmd+shift+w closes the app window.

Dnia 9 kwi 2015 o godz. 08:49 Peter Renström notifications@github.com napisał(a):

**Comment by joshpuckett** [comment]
Added cmd+w to close!
