### ISSUE TITLE
Remove Black Banner for installing messenger app on phone

### ISSUE THREAD

**Issue by xrisk** [rsms/fb-mac-messenger#151]
![screen shot 2015-06-28 at 7 04 29 pm](https://cloud.githubusercontent.com/assets/10669859/8396555/ae89ae6a-1dc8-11e5-80b4-39dd3b2da21e.png)

**Comment by dfosco** [comment]
+1

For god's sake, please remove it — I even have the mobile app installed, no need for this ad bolted into the UI.

**Comment by rsms** [comment]
Then this is a bug with messenger.com and not this app. https://www.facebook.com/help/messenger-app/248748738662378 (messenger.com > gear > Report a Problem)
