### ISSUE TITLE
"Sounds" setting does not work - always play sound effect

### ISSUE THREAD

**Issue by reverbc** [rsms/fb-mac-messenger#152]
The "Sounds" setting in Preferences pane is not working properly.
Once I turn on Desktop Notification, no matter I enable or disable the sound it always play.

The issue can be reproduced in my 2 Macs (MBA and MacBoook Pro, all running latest 10.10.3) with latest release build (0.0.9).

**Comment by rsms** [comment]
I'm guessing you have desktop notifications enabled and haven't disabled the sound in syspref?

<img width="780" alt="screenshot 2015-08-12 19 46 14" src="https://cloud.githubusercontent.com/assets/47046/9241637/d0bcc9b0-412a-11e5-9878-2010935a0d84.png">
