### ISSUE TITLE
Cannot move window in OS X El Capitan (10.11 Beta)

### ISSUE THREAD

**Issue by GibStorm** [rsms/fb-mac-messenger#156]
Just upgraded to the public beta of OS X El Capitan. Now I cannot move the window of the application. Everything else seems to work fine, though.

**Comment by devanhurst** [comment]
Strange. I wasn't having this problem on 10.11 until I read this post. I can't move the window using the header, but have almost 100% success when moving on the wrong axis with the resizing arrows.

**Comment by palkoc** [comment]
The same here. Once the messenger page is loaded, it disables the window movement. Still persisting in Beta 4

https://www.youtube.com/watch?v=E-WC-KVAJ28

**Comment by iMerica** [comment]
I'm seeing the same issue. Is there a workaround?

**Comment by GibStorm** [comment]
I don't think this can be fixed before after the final release of El Capitan (and in extension the new version of Xcode). To my knowledge, there is no workaround for this.

**Comment by bpwned** [comment]
Perhaps you can take a look at https://github.com/danielbuechele/goofy/ to see how they avoided the issue.

**Comment by AndreasBackx** [comment]
It also happens on Beta 7 in case anyone was wondering.

**Comment by rsms** [comment]
Very weird. Someone with 10.11 and Xcode, clone the repo, open the xcode project, find "- (void)updateWindowTitlebar" in AppDelegate and remove all code in the method (or just "return" on the first line) and build & test the app.

Because of the non-standard titlebar height, this app performs some funky view modifications which might break in 10.11.

**Comment by iMerica** [comment]
For anyone still annoyed by this: you can get the exact same functionality with this Chrome Extension:

https://chrome.google.com/webstore/detail/app-launcher-for-messenge/bllmngcdibgbgjnginpehneeofhbmdjm

**Comment by calumk** [comment]
Just to follow up with this, removing code in -(void)updateWindowTitlebar does not solve this issue

**Comment by spyesx** [comment]
Maybe someone could just restore the default top bar. It's not a big deal to hide it or not.
I'd like to help but I'm not iOS/OSX developer. If anybody can do it in a fork :)

**Comment by polidore** [comment]
+1

**Comment by wez** [comment]
Same here.  Additional data point though: if you focus a different app, you can then click and drag the title area to move the window around.  After Messenger gains focus, the title bar dragging behavior is lost.

**Comment by infilmity** [comment]
10.11 GM still cannot move.

**Comment by rsms** [comment]
If someone on 10.11 could provide a fix for this, that would be great.

**Comment by dapetcu21** [comment]
Gonna give it a go here since it's god damn unusable this way.

**Comment by rsms** [comment]
@dapetcu21 :+1:

**Comment by rsms** [comment]
**FYI:** Work on building against 10.11 SDK is happening in this branch: https://github.com/rsms/fb-mac-messenger/tree/OSX10.11

**Comment by dapetcu21** [comment]
Close this now or when you merge OSX10.11 into master?

**Comment by joshwertheim** [comment]
FWIW, I just installed public OSX10.11 as well and this issue still happens.

**Comment by dapetcu21** [comment]
I think it needs a merge and a release?

Marius Petcu,
Software Engineer at LearnFwd
IT & Media Manager at ARGO Debate

**Comment by pierloui** [comment]
Still happening with final 10.11 release...

**Comment by palkoc** [comment]
Hi,
use this version: Download development release (for OS X 10.11)
http://fbmacmessenger.rsms.me/dist/Messenger-dev.zip

This one works fine on 10.11

Pavol

**Comment by iMerica** [comment]
Hi @palkoc,

You're asking users to enter their Facebook login credentials into an unsigned package located an an unsecure URL. If this is a dev release, can we use [Github's built-in tools](https://github.com/blog/1547-release-your-software) for releasing software to the public? It's safer for everyone.

Thanks,

Michael

**Comment by palkoc** [comment]
As the author already mentioned, you can git clone the repository, switch
to OSX10.11 branch, change the Deployment Target to 10.11 and the project
will compile without errors.

Pavol

**Comment by rsms** [comment]
Assuming this is no longer an issue
