### ISSUE TITLE
El Capitan beta 3 issues

### ISSUE THREAD

**Issue by homoky** [rsms/fb-mac-messenger#157]
1) window is not draggable

2) when i launch app it works great, but when it reloads, this happens to left sidebar: 

![screenshot 2015-07-12 v 12 50 49](https://cloud.githubusercontent.com/assets/893917/8637515/c3502c80-2894-11e5-86ec-efeca09d1c7b.png)

**Comment by spyesx** [comment]
Same for me but it looks like a build from the new xcode could fix it. I'm not an iOS dev but my OS keeps asking for a new version of xcode that I can't download yet.

**Comment by loonghuey** [comment]
The problem seems to persist when you open messenger.com with Safari, so I guess it's nothing @rsms can fix?

**Comment by homoky** [comment]
Yes, you are right. In Safari helps when I change broswer agent to Chrome for example.

**Comment by rsms** [comment]
Is this still an issue? The Messenger.com team continually makes improvements.

**Comment by irae** [comment]
Not dragging is still an issue in El Captain beta 5. The reload issue don't exist anymore.
I think the issue can be renamed to "Impossible to drag window in El Captain Beta".

**Comment by rsms** [comment]
Duplicate of #156
