### ISSUE TITLE
No refresh of conversations

### ISSUE THREAD

**Issue by onimaca** [rsms/fb-mac-messenger#159]
The app is not refreshed automaticly if i write a message from other place(mobile, chrome...) i have to click reload from server and it is updated then

I tried to delete all safary cookies, history... but it didnt work

**Comment by lightheaded** [comment]
+1

**Comment by rsms** [comment]
Issue with messenger.com

**Comment by unitbroker** [comment]
New job with southern Cali apparel manufacturer
Here's a 5$ coupon. http://shop.pe/iD1nT
If I sell $500 dollars by 5pm x-apple-data-detectors://2 I keep my lights
on!
We have really cool stuff!
Have a good weekend!

On Tuesday, July 14, 2015, onimaca notifications@github.com wrote:

> The app is not refreshed automaticly if i write a message from other
> place(mobile, chrome...) i have to click reload from server and it is
> updated then
> 
> I tried to delete all safary cookies, history... but it didnt work
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rsms/fb-mac-messenger/issues/159.

## 

Rob Estes
Ipad_1
Unitbroker@gmail.com
602-319-4052
