### ISSUE TITLE
Slack style conversation switcher

### ISSUE THREAD

**Issue by eladg** [rsms/fb-mac-messenger#160]
Hey @all ;)

Would love to know if anyone else is interested in Slack style conversation switcher.

On Slack: ⌘K and start typing will show a list of possible matches and pressing enter will select the specific conversation.

Is this exist and I missing it? Anyone else interested in such feature?

**Comment by asherism** [comment]
That is outside of the scope. The intention is to simply provide Messenger on the desktop as-is.

**Comment by rsms** [comment]
Have you tried ⌘F? It's very similar

**Comment by eladg** [comment]
Yes, I ended up using ⌘F with the official version, but the ⌘F + name + ⌘1 flow is kinda weird in my taste, would have prefer pressing enter (or something) instead of ⌘1

**Comment by rsms** [comment]
wontfix
