### ISSUE TITLE
Why the app tried to connect to consumerfinance.gov?

### ISSUE THREAD

**Issue by littlecho** [rsms/fb-mac-messenger#162]
I just downloaded the latest version from the website and found the app trying to make connection to "www.consumerfinance.gov:443" while launching. Can somebody explain it? Thanks!

<img width="694" alt="2015-07-22 11 20 37" src="https://cloud.githubusercontent.com/assets/688729/8817276/1caf3556-3064-11e5-9d5b-38bf2d17bbb4.png">

**Comment by kevincannon** [comment]
Indeed.

Also, I got facebook alerts saying that I just logged in from Tokyo, and also Texas (I'm in Europe) so there's something dodgey going on with this.

**Comment by rsms** [comment]
You guys might have viruses in the form of Safari extensions. Remember, this app is just a web view (i.e. Safari) that loads messenger.com. If you got alterts saying you logged in from (or attempted to log in from) someplace you didn't, always report it to Facebook and they'll look at what's going on (I used to work at Facebook, and there are definitely people looking in to stuff like that.)

When it comes to this app, feel free to browse the source code. You can also easily classdump and/or strings etc the distribution (it's not stripped) to verify there's no undisclosed code in the dist.

**Comment by kevincannon** [comment]
Could be, but I don't get the same issue with Safari at all. I don't even use Safari, so have only 1 plugin installed (1Password)

Not saying there's anything sinister with the source code, but perhaps something weird is causing this.
