### ISSUE TITLE
Desktop notifications turn off as soon as the app is closed and have to be turned on again each time it's opened

### ISSUE THREAD

**Issue by deusy** [rsms/fb-mac-messenger#163]

**Comment by rsms** [comment]
Can't reproduce.
Please provide detailed steps on how you reproduce this along with what exact OS version you're using. Thanks.

**Comment by deusy** [comment]
OS X Yosemite 10.10.3

Here's exactly what happens:
1. Open app
2. Cmd-, to open preferences
3. Press "Turn on desktop notifications" so it becomes to "Turn off desktop notifications"
4. Exit settings
5. Desktop notifications work while app is open
6. Close app and reopen
7. Cmd-, to open preferences
8. Preferences says "Turn on desktop notifications" again, and they need to be turned on for notifications to work

**Comment by rsms** [comment]
Weird. I can't reproduce, but try to remove the localstorage state by — in the app — right-click somewhere, choose "inspect element", then go to the console and enter "localStorage.clear()" in the console input, then immediately quit and restart the app.

**Comment by ashokfernandez** [comment]
I get this too. Not able to get a context menu by right clicking, is there something I need to do to make this show up?

**Comment by ghost** [comment]
same issue@mac os x v10.11.2

**Comment by rsms** [comment]
messenger.com most likely changed the way they store state about notifications being enabled. The app attempts to configure notifications on/off state on start at https://github.com/rsms/fb-mac-messenger/blob/v0.1.5.2015-09-18_00-28-36/Messenger/AppDelegate.mm#L829

Essentially `localStorage.getItem('_cs_desktopNotifsEnabled')`

I haven't had time to look into it yet.

**Comment by hrubymar10** [comment]
Same

**Comment by chalkos** [comment]
Same here. Also I could not get a context menu by right clicking.

**Comment by vikeri** [comment]
Confirmed issue here as well

**Comment by rsms** [comment]
Known issue. Only proper fix is to migrate to WKWebView.
Release 0.1.6 introduces a temporary fix to this.
