### ISSUE TITLE
Dragging an image directly into the chat view

### ISSUE THREAD

**Issue by mchen046** [rsms/fb-mac-messenger#164]
Dragging an image directly into the chat view sometimes causes the image to send twice.

**Comment by deusy** [comment]
+1

This has happened to me on a number of occasions. I've avoided it by just sending images through the file upload button, but drag and drop is much easier.

**Comment by sethk** [comment]
Messenger.com now has a drop handler that duplicates the functionality of main.js. Please see my pull request.
