### ISSUE TITLE
App keeps freezing

### ISSUE THREAD

**Issue by beckynoel** [rsms/fb-mac-messenger#165]
The app's been working great for me the past few weeks, but the past few days it's intermittently freezing, requiring me to close the app completely and re-launch.  Any ideas? 

When it freezes, I just get the circle like it's "processing" and it times out on my mac.  If I try to wait for the app to come back, it just keeps "processing".

**Comment by rsms** [comment]
Weird. "Circle" as in the Facebook loading spinner or as in Mac beachball? Is the app unresponsive or is messenger.com unresponsive? (attempt to right-click — if a context menu appears, the app _is_ responsive.)

Have you used the app in Safari for longer periods of time? If so, have you experienced similar issues? You might have some plugin/extension installed in Safari (this app uses a "Safari" webview, meaning that most settings in Safari affect this app)

**Comment by unitbroker** [comment]
New job with southern Cali apparel manufacturer
Here's a 5$ coupon. http://shop.pe/iD1nT
If I sell $500 dollars by 5pm I keep my lights on!
We have really cool stuff!
Have a good weekend!

On Tuesday, July 28, 2015, beckynoel notifications@github.com wrote:

> The app's been working great for me the past few weeks, but the past few
> days it's intermittently freezing, requiring me to close the app completely
> and re-launch. Any ideas?
> 
> When it freezes, I just get the circle like it's "processing" and it times
> out on my mac. If I try to wait for the app to come back, it just keeps
> "processing".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rsms/fb-mac-messenger/issues/165.

## 

Rob Estes
Ipad_1
Unitbroker@gmail.com
602-319-4052

**Comment by rsms** [comment]
dead
