### ISSUE TITLE
Panels 

### ISSUE THREAD

**Issue by nzjoel** [rsms/fb-mac-messenger#166]
Within the last week, the left column that contains the list of conversations has gotten wider and I am unable to resize it. Im not sure if you could ever resize it, but now its wider its something I would like to make smaller again. The reason I noticed is because I use half of my laptop screen for the FB Messenger app and the other half for the Mac Messenger app, and when you have both side by side, there isnt room for the conversation list to be wider than 1/4 the width of the screen. 

Has Facebook changed the width of this column, was it a change to the app? Can it be made resizable? 

![fullscreen_03_08_2015_20_25](https://cloud.githubusercontent.com/assets/1848200/9045796/0dffea1e-3a1e-11e5-99e9-6e9d9960df52.png)

**Comment by chenglou** [comment]
I "broke" it by revamping some of our messenger.com layout code. I'm not sure what the wrapper does under the hood, but ironically I use this wrapper and now it looks weird. Feeling guilty.

**Comment by tarikd** [comment]
Happy to see that some messenger.com developers use this wrapper ! I hope that you will find a way to allow the layout code for the contact panel to be responsive again in the future :smile:

**Comment by chenglou** [comment]
=) Just to clarify: the layout is responsive and works correctly on messenger.com We've also introduced the mini inbox view which saves a lot of screen estate for smaller screens.

As for the wrapper, I think it does the style overriding? Haven't checked into this much yet. If it's a plain web view then it shouldn't have broken anything.

**Comment by tarikd** [comment]
I thought that all style overriding has been removed from the wrapper... Maybe @rsms might have an idea ?

**Comment by chenglou** [comment]
Is there any user agent spoofing going on here? @rsms this _might_ be a quick fix.

**Comment by sethk** [comment]
@chenglou, are you implying that the conversations list should be drag-resizable on messenger.com in Safari or Chrome on Mac right now? Because I can't get it to work.

**Comment by chenglou** [comment]
No, it auto resizes depending on your viewport size.

I've received a few by reports on wrappers being broken and it's mostly because they spoof the user agent. I've made a small change that fixed the Fluid.app wrapper but this wrapper's problem seems to be elsewhere.

**Comment by sethk** [comment]
@chenglou, your first instinct was correct; the User-Agent doesn't contain the word "Safari," and that broke the sizing. I'm working on a pull request.

**Comment by tarikd** [comment]
:+1:

**Comment by rsms** [comment]
@chenglou The app is a simple standard WebView which loads this file that does a small mount of JS modifications: https://github.com/rsms/fb-mac-messenger/blob/master/website/app/main.js

Inspecting the sidebar in Safari, it seems it receives the CSS class ".safari.webkit ._1enh" with `-webkit-flex:0 0 25%;` — however, when messenger.com is loaded in this app's WebView, it does not receive the same CSS class.

My guess is that the user agent of a WebView is something like `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko)` while for Safari it contains "Safari" which might be tested for to enable native flexbox (rather then checking the webkit version for flexbox support)

**Comment by chenglou** [comment]
I test for `.safari.webkit`, so that's why. I think you can change the user agent of the webview to match safari 8's.

**Comment by rsms** [comment]
@chenglou Done by @sethk in #175 which I just verified to work and merged. Yay!

**Comment by chenglou** [comment]
Awesome. Sorry for the trouble. I'm converting things to flexbox so layout's been a bit shaky across the many native wrappers. There are still a bit of layout conversion left but I'll keep an eye on the wrappers.

**Comment by nzjoel** [comment]
All fixed now! Thanks for the resolution, looking better than ever :)
