### ISSUE TITLE
I want text search

### ISSUE THREAD

**Issue by szhu** [rsms/fb-mac-messenger#173]
1. The menu item to activate "Search for people and groups" should be named exactly that, or "Filter conversations" (à la Activity Monitor) instead of "Find", and its key equivalent should be ⌘⌥F instead of ⌘F. Also, as in Activity Monitor, this menu item should be under View, not Edit.
2. I assume WebKit provides the Find Panel functionality for free, since the menu options are there. Please bring it back so I can search within conversations. (I know that it will match UI text, but I'd rather have that than no text search at all.)

**Comment by rsms** [comment]
1. Good point. It was added w/o renaming the menu item. We should move and rename it.
2. No, unfortunately not — a webview does not give you the find bar or even a find panel for free. It's been a long-planned feature (google it.)
