### ISSUE TITLE
⌘W should be inverse of ⌘N

### ISSUE THREAD

**Issue by szhu** [rsms/fb-mac-messenger#174]
In every app that has ⌘N, ⌘W after ⌘N will undo it. Not so in this app. Two suggestions:

Option 1: Conversations are primary; treat them like tabs.

| key | does |
| :-- | :-- |
| ⌘⇧W | close window |
| ⌘W | nothing, because conversations can't be closed |
| ⌘N | new conversation |

Option 2: The window is primary.

| key | does |
| :-- | :-- |
| ⌘W | close window |
| ⌘N | new window? |
| ⌘⌥N? | new conversation |

**Comment by rsms** [comment]
Yeah, this is tricky. ⌘N really should be new conversation, as that's the "unit" that can be created in Messenger. The app actually only hides the window on ⌘W, making it possible to allow cmd-shift-w or simply cmd-z to show the window again. Could also make ⌘N show the window if the window is hidden.

**Comment by szhu** [comment]
Using ⌘⇧W to show the window doesn't really make sense. I don't see any
precedents; let me know if there are any.

⌘Z to "undo" closing/hiding something I've only seen in Safari, and I really
hate it because it activates sometimes when I expect ⌘Z to be limited to text
operations. It's not intuitive to most users because most other apps do not
follow it.

Btw, I was wrong about my initial statement that ⌘W is always the inverse of ⌘N:
it actually isn't so with Apple's own Messages app.

| key | does |
| --- | --- |
| ⌘N | New Conversation |
| ⌘W | Close Window |
| ⌘⇧W | Close Conversation |
| ⌘0 | Messages (ensure window is visible) |

Furthermore, all keys that cause change in the main window will also make it
visible. Two new suggestions:

Option 1: Follow messages

| key | does |
| --- | --- |
| ⌘N | New Conversation (and ensure window is visible) |
| ⌘W | Close Window (hide window) |
| ⌘0 | Messages (ensure window is visible) |

Option 2: Follow web browsers: ⌘W is inverse of ⌘N

| key | does |
| --- | --- |
| ⌘N | New Conversation (and ensure window is visible) |
| ⌘⇧W | Close Window (hide window) |
| ⌘0 | Messages (ensure window is visible) |

**Comment by rsms** [comment]
"Close Conversation" doesn't apply to Messenger (there's nothing to close, only "Delete".)

I'm using OS X 10.10 and my Messages.app doesn't have a "Close Conversation" option. Are you running 10.11?

**Comment by szhu** [comment]
You need this option enabled in preferences:
![screen shot 2015-08-13 at 10 12 40 am](https://cloud.githubusercontent.com/assets/1570168/9241281/eeaf7fac-41a3-11e5-9218-bd3f1b6615c4.png)

**Comment by rsms** [comment]
Oh. I just keep all of them "open".

**Comment by szhu** [comment]
Yeah same with most people, which is probably why that's unchecked by default. But that option isn't really relevant because Messenger doesn't have that option. (Facebook allows message archiving, but it's not on Messenger yet. Also it's niche and people invoking ⌘W might be surprised to see conversations disappear.)

**Comment by szhu** [comment]
Actually, there is a use for "Close Conversation." It is, of course, the inverse of ⌘N:

![screen shot 2015-08-14 at 10 37 59 pm](https://cloud.githubusercontent.com/assets/1570168/9276343/e05b9994-42d5-11e5-8610-c95f9a511e62.png)

**Comment by rsms** [comment]
But only for temporary drafts, not actual conversations.

**Comment by szhu** [comment]
Yes, only when it still reads "New Message".

**Comment by szhu** [comment]
Hello, I'm closing this issue since this repo isn't updated anymore. If anyone seeing this issue is looking for an alternative app, I currently use Caprine (https://github.com/sindresorhus/caprine), which does the same thing using similar technologies and is also open source.

I'd like to note that while Caprine (and numerous other clones) might be more modern, I believe this repo was the first really successful one (if not the first one altogether) -- many thanks to @rsms for being the first to make a simple, well-designed webview-based Messenger app.
