### ISSUE TITLE
About Messenger needs to show version number

### ISSUE THREAD

**Issue by szhu** [rsms/fb-mac-messenger#176]
99% of the time when I click the "About App" menu item, it is to check for a version number. Also, users might want to know where the app is from. I doubt users who downloaded this app really need to know what messenger is. In addition, I have never observed a non-technical user choosing that menu item unless being told to do so as part of tech support, in which case they need to select the item to check for the version number.

Suggestions:
- Option 1, preferred: Change "About Messenger" back to the standard about dialog. Add "About Messenger.com" to the Help menu.
- Option 2: Add version number to the top of the title of the current "About Messenger" window.

**Comment by lucijafrkovic** [comment]
I agree, there's no way of finding out where the app came from, it appears as if it's an official app.

**Comment by rsms** [comment]
FYI: If you select "Check for updates" in the main menu, the dialog will respond with something like "Messenger 0.1.4 is currently the newest version available."

However, that does not include the build timestamp. bd94ecd adds the full version to the about window title.

You can also read the version from it's bundle info:

```
$ /usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' \
  /Applications/Messenger.app/Contents/Info.plist
0.1.4.1440786644
```

**Comment by szhu** [comment]
Thanks! For those reading who really want to know the version without opening the app and without Terminal, you can Get Info the app :)

<img width="377" alt="screen shot 2015-09-14 at 7 04 36 pm" src="https://cloud.githubusercontent.com/assets/1570168/9866121/78ed314a-5b13-11e5-8bbd-4ddaa1150b4e.png">
