### ISSUE TITLE
Add min-width property

### ISSUE THREAD

**Issue by zenVictor** [rsms/fb-mac-messenger#18]
Add a property of minimum width of the window. Right now I can make window like on the screenshot.
And also this settings button and Mac buttons together don't feel good.

![screen shot 2015-04-09 at 9 46 10 am](https://cloud.githubusercontent.com/assets/7612779/7061697/ea419964-de9d-11e4-99f7-d2903aaa25cf.png)

**Comment by joshpuckett** [comment]
Resolved in latest commit!
