### ISSUE TITLE
Cursor skips backwards one character upon pressing space

### ISSUE THREAD

**Issue by ghost** [rsms/fb-mac-messenger#181]
This is kind of weird and a tad bit difficult to describe. To reproduce:
- Start typing in the "Type a message..." textbox
- Type any number of non-whitespace characters. The text cursor tracks the text as expected.
- Press the space bar once
- Type one non-whitespace character. The cursor stops tracking and lags behind by one character.
- Type another non-whitespace character. The cursor begins tracking the text again.

I screen captured the behaviour into an animated GIF, which should clarify everything:
![weird cursor behaviour](https://cloud.githubusercontent.com/assets/3952835/9485632/22011484-4b71-11e5-9201-2ec8954fade0.gif)

It seems like the custom document.body.onkeypress handler is the culprit. I disabled the handler in the console by setting document.body.onkeypress to null and it fixed the issue. (Yes, that keypress _beep_ occurs but it was better than getting garbled text.)

The following hack, which prevents the handler from executing when the space bar is pressed, seems to work as well. For some reason spaces don't play well with your custom event?

```
document.body.onkeypress = function (e) {
    if (e.target.contentEditable && !e.metaKey && e.which !== 32) { // don't execute for spacebar presses
        e.preventDefault();
        var textEvent = document.createEvent('TextEvent');
        textEvent.initTextEvent('textInput', true, true, null, String.fromCharCode(e.which));
        e.target.dispatchEvent(textEvent);
    }
};
```

**Comment by mjuarez** [comment]
Experiencing this as well.

**Comment by yangshun** [comment]
Yes started experiencing this today. Not sure why.

**Comment by tadaszelvys** [comment]
Just started experiencing this annoying thing.

**Comment by JLGouwy** [comment]
Me too ! just started this morning ... :(

**Comment by kristoffeys** [comment]
+1

**Comment by tarikd** [comment]
:+1:

**Comment by n2k** [comment]
:+1:

**Comment by n2k** [comment]
if you start your message with a space it works but then delete and backspace doesn't work :/

**Comment by nManscher** [comment]
+1

**Comment by hrubymar10** [comment]
+1

**Comment by coreydunkin** [comment]
+1

**Comment by ThomasMela** [comment]
Me to :'(

**Comment by lindesvard** [comment]
Same same...

**Comment by Flowdeeps** [comment]
+1

**Comment by sstadick** [comment]
Also getting this.

**Comment by nick-barth** [comment]
+1

**Comment by zebapy** [comment]
+1

**Comment by rpierreye** [comment]
:+1:

**Comment by rodrigomuniz** [comment]
+1

**Comment by ashokfernandez** [comment]
+100

**Comment by ericthor** [comment]
+1 Started today for me as well.

**Comment by nzjoel** [comment]
+1 makes the app unusable :cry:

**Comment by aqhillie** [comment]
Same here.

I believe this has started happening since I last updated this from the new version which it detected yesterday or the day before.

**Comment by wickles** [comment]
@alexquintana I was still on 1.0 but had the same issue this morning, so I'm not sure it's due to a newly introduced bug. Maybe facebook API changes or something?

**Comment by rsms** [comment]
It seems facebook changed something which triggered some bug in this app. Any ideas to what's going on would be appreciated :)

**Comment by MWYang** [comment]
+1

**Comment by rsms** [comment]
The app's main.js file has been published, meaning you'll need to simply restart the app for the bug to go away. (Messenger > Reload app from server) No need to install a new version of the app.

**Comment by loneshaman** [comment]
I'm still getting the issue, even after reloading.

**Comment by MWYang** [comment]
I had to restart the app as well. (Cmd + Q, then launch again.)

**Comment by wickles** [comment]
Issue is not resolved for me. I've reloaded from server and restarted the app several times.

**Comment by ghost** [comment]
~~Hmm.. it seems like restarting the app and "Messenger > Reload app from server" isn't downloading a new version of main.js...~~

~~Manually editing main.js in Contents/Resources to include your fix (https://github.com/rsms/fb-mac-messenger/commit/87fd037214e9167e20523ca575426df0da23d0f0) works though.~~

Seems to be just a delay/timing thing.

**Comment by loneshaman** [comment]
I reloaded the app a few more times and then the fix went through. Might just be a timing thing.

**Comment by rsms** [comment]
The main.js file is subject to regular caching strategies of whatever webkit version your system happens to use. When we create new native app distributions, we add that app's tree hash to the main.js file (as a query string) to force wk not to used a cached version. There are some small fixes on their way in, and once they're in, a new dist will be created and it will force the use of a new main.js

**Comment by rsms** [comment]
A new release has shipped that forces reload of the new main.js

Messenger > Check for updates...
