### ISSUE TITLE
Add stealth mode to disable "seening" in conversations.

### ISSUE THREAD

**Issue by caseyls** [rsms/fb-mac-messenger#183]
I have an "seen blocker" for facebook extension on both chrome and safari that lets me look at facebook messages without notifying the other person that I've "seen" them. It would be super cool if a similar functionality could be added as a switch in this app. 

Obviously super low priority but just thought I'd throw it out there.

**Comment by rsms** [comment]
Seen receipts are an integral part of Messenger and will not be circumvented by this app.

wontfix
