### ISSUE TITLE
Using app password to log in fails

### ISSUE THREAD

**Issue by mirfilip** [rsms/fb-mac-messenger#185]
Hi, in order to log in, I generated an "application password" dedicated for this app. Using my @ as a login and this password fails. The result is "The password you entered is incorrect" message. I have 2FA enabled. Any ideas?

**Comment by rsms** [comment]
Does it your app password work with messenger.com if you open a new private window in Safari?

**Comment by rsms** [comment]
FTR, I've got 2fa as well and sign in to messenger.com with my username (rsms) but do use my regular password + 2nd auth (not using app password.)

**Comment by mirfilip** [comment]
Indeed, it doesn't. Consider this ticket invalid until I do a little research on that. Thanks!
