### ISSUE TITLE
Permanent banner: "Keep the conversation going from your phone"

### ISSUE THREAD

**Issue by tbnv** [rsms/fb-mac-messenger#186]
Hello,

This banner "Keep the conversation going from your phone" appears permanently on top of the app (and it is also present on messenger.com of course). See capture.

Anything we can do about that?

![](http://shrrr.it/sobftsba4u_image.png)

**Comment by kinduff** [comment]
:+1:, got it too. This comes from the messenger.com and there's no button to close it. Class is `_s15`, so app CSS could help hidding it.

**Comment by kinduff** [comment]
Related, but not in this repo: https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/74af9c6c3716b1e5dc9e5f87b600b99eccef911d

**Comment by rsms** [comment]
Relying on CSS classes doesn't work. The code in the project you referenced will definitely break as Facebook's CSS classes are machine-generated and—just like inferred React IDs—are relative to the context of a given element's CSS class. (I used to work at Facebook)

Anyhow, clearing this banner should be easy with a well-crafter querySelector query.

I can't fix this as I don't have the banner, but someone who does should patch main.js and submit a pull request.

**Comment by bradreardon** [comment]
@rsms I signed into an old Facebook account. For your information, here's the React tree that results in that banner. Since it's not always present, I'm not sure how to hide it myself since my Obj-C and React skills are limited.

<img width="1257" alt="screen shot 2015-09-26 at 2 44 31 pm" src="https://cloud.githubusercontent.com/assets/225906/10119220/29706f76-645d-11e5-81ee-826babbe7108.png">

**Comment by rsms** [comment]
Would be happy to accept a patch/PR for this

**Comment by bradreardon** [comment]
@rsms The above PR fixed it on my old account.

**Comment by jmcbee** [comment]
This is appearing again.

![adios motherfucker](https://i.imgur.com/6MrMUg4.png)

**Comment by jmcbee** [comment]
![](https://i.imgur.com/qCT1wpZ.png)
