### ISSUE TITLE
No Minimize, Maximize, or Close buttons on the top of the app window

### ISSUE THREAD

**Issue by redfox05** [rsms/fb-mac-messenger#190]
On Mac OSX 10.9.5, there are no buttons in the top left corner of the app to allow you to minimize the app. The only button on the window bar is the "Fullscreen" button, which won't help the minimize issue. This is very frustrating as when you are working you want to be able to check messages, quickly reply, minimize thje app, and go back to work.

Instead, as a workaround, I have to click on >Window > Minimise, which takes a lot more time and sometimes stops me from checking Messenger at all when im very busy.

This should be a fairly simple fix surely? Is it not a case of enabling a flag in the app settings to enable these buttons? I may be wrong, I dont do Mac App Development, I'm a front end web developer myself.

Hope you can fix it soon. And despite my issue above, I do think this is a great app, and even with this bug, its fantastic! Thanks!! :)

System: Mac OSX 10.9.5

**Comment by redfox05** [comment]
<img width="648" alt="screen shot 2015-09-16 at 18 52 10" src="https://cloud.githubusercontent.com/assets/7571495/9913362/63dafbba-5ca4-11e5-96fb-3743fc60cb4d.png">
Screenshot attached.

**Comment by rsms** [comment]
What version of OS X are you using? Looks like you're on 10.9 which is currently untested.

**Comment by redfox05** [comment]
Yep I'll try and get that for you. I cut out the rest of the screenshot as
it had personal data and messages, but I'll figure a way around that as you
need it.

Edit: Thats odd, my reply here was to your request for a screenshot, but it doesnt appear on github anymore. Did you remove it? Did you still need screenshots?

_rsms:_
_What version of OS X are you using? Looks like you're on 10.9 which is currently untested.
Also, would you mind posting a screenshot of the actual app showing what you see? Thanks._

**Comment by redfox05** [comment]
View of the app:
<img width="636" alt="screen shot 2015-09-17 at 09 01 50" src="https://cloud.githubusercontent.com/assets/7571495/9928028/e2960d8e-5d1a-11e5-9476-2ef94e77b1b1.png">

Mac OS Version info (10.9.5):
<img width="344" alt="screen shot 2015-09-17 at 09 03 09" src="https://cloud.githubusercontent.com/assets/7571495/9928041/fe3a9fa0-5d1a-11e5-8a77-8b9e890778c4.png">

Happy to do more testing for you if you need to. You're lucky I've not made the switch to Yosemite yet, ive been too busy :-P I take it it works fine in Yosemite?

**Comment by rsms** [comment]
The app does no longer support 10.9.
You can use version 0.1.4 http://fbmacmessenger.rsms.me/dist/Messenger-0.1.4.1440786644-f3436781b1e02ea1.zip for 10.9 support
