### ISSUE TITLE
On 10.11 with the 10.11 SDK, Safari won't allow mixed content.

### ISSUE THREAD

**Issue by dapetcu21** [rsms/fb-mac-messenger#191]
I was looking to fix #156 and I stumbled upon something else while trying to compile the app. Initially, it wouldn't let me load anything, so I discovered I have to add something `NSAppTransportSecurity`-related in `Info.plist`. Now, Safari won't let me load http (or even resource://) content in a https page.

<img width="845" alt="screen shot 2015-09-17 at 22 23 41" src="https://cloud.githubusercontent.com/assets/428060/9943630/46015d18-5d8b-11e5-8cad-9c9401f899cc.png">
<img width="735" alt="screen shot 2015-09-17 at 22 22 29" src="https://cloud.githubusercontent.com/assets/428060/9943631/4632ab48-5d8b-11e5-93ed-5ecba8e68236.png">

The only workaround I found is

``` objective-c
auto mainJSURLString = [NSString stringWithFormat:@"data:application/x-javascript;base64,%@",
                        [[NSData dataWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"main" ofType:@"js"]] base64EncodedStringWithOptions:0]];
```

Now, that won't work in release builds where we're serving `main.js` from `http://fbmacmessenger.rsms.me` because it would mean doing a network call synchronously, which would hang the app on bad connections.

Any suggestions? What do I commit? Unless you have a HTTPS cert, I propose loading main.js from the app bundle even in release builds.

**Comment by rsms** [comment]
Work on building against 10.11 SDK is happening in this branch: https://github.com/rsms/fb-mac-messenger/tree/OSX10.11

**Comment by dapetcu21** [comment]
Oh. Thanks. I wouldn't have noticed it.
