### ISSUE TITLE
Bad title bar button placement after coming out of full screen on 10.11

### ISSUE THREAD

**Issue by dapetcu21** [rsms/fb-mac-messenger#194]
<img width="399" alt="screen shot 2015-09-18 at 11 55 21" src="https://cloud.githubusercontent.com/assets/428060/9955789/5e645c90-5dfc-11e5-9970-5d59d8bfe299.png">

Resizing the window (`-updateWindowTitlebar` getting called) fixes it.
I noticed this while working on #156, so I'll take a look tonight.

**Comment by rsms** [comment]
Fixed in release 0.1.6
