### ISSUE TITLE
Time is hidden by delete button when message right clicked.

### ISSUE THREAD

**Issue by mdcanham** [rsms/fb-mac-messenger#196]
When right clicking on larger messages to view the time that it was sent/received the time is covered up by the delete button.

<img width="383" alt="screen shot 2015-09-21 at 11 19 32 pm" src="https://cloud.githubusercontent.com/assets/8162764/9990682/418aa986-60b7-11e5-9e57-fc21f7ac4e5b.png">

**Comment by rsms** [comment]
"Bug" in messenger.com
