### ISSUE TITLE
New conversation icon underneath close/minimize/full screen icons

### ISSUE THREAD

**Issue by nzjoel** [rsms/fb-mac-messenger#198]
When you have the window relatively narrow enough that the left panel collapses just to circul profile photo icons, the new conversation icon is overlapped by the mac close/minimize/full screen icons. It's still clickable but it's overlapped and harder to press.

I'd expect the new conversation button to be pushed down.

See:
![screen shot 2015-09-21 at 22 24 12](https://cloud.githubusercontent.com/assets/1848200/10005991/4fc12de0-60b2-11e5-82b5-2e751289093a.png)

**Comment by bradreardon** [comment]
Attempted to fix this, but it got late. Anyone who wants to look at the above commit and offer some guidance, go ahead. Obj-C and JS (esp. React) aren't really my strong suits, just wanted to make an attempt to help out.

**Comment by nzjoel** [comment]
![screen shot 2016-02-11 at 11 05 02](https://cloud.githubusercontent.com/assets/1848200/12974867/533bf9ce-d0af-11e5-8a47-b6526ce3d379.png)
Looks and works great!
