### ISSUE TITLE
Add support for tray/menu bar icon

### ISSUE THREAD

**Issue by juliovedovatto** [rsms/fb-mac-messenger#204]
Great app, very functional. But is a little difficult to me to see when someone sends me a message. 

Other chat apps has a option to put a icon on the tray/menu bar and gets a color when someone sends a message. 

I know there is a Notification option, but I don't like the notification window every moment to notify me, it's annoying :(

Cheers!

**Comment by elitzer2** [comment]
There is a dock icon that has a number of unread messages counter. Do you not see this?

**Comment by juliovedovatto** [comment]
@elitzer2 I prefer to auto hide the OSX dock, to gain more space to work with.

**Comment by zethussuen** [comment]
Might consider: https://github.com/maxogden/menubar

**Comment by rsms** [comment]
wontfix
Status items (technical name) are well-defined by Apple HIG to be used for status applications like wifi connection, Dropbox sync status, etc. This is a messaging app.

**Comment by ciembor** [comment]
@rsms I think it should be available to enable status item with. I don't know the apple HIG, but if it defines status items as something "like" other apps, than it's not well defined. Every service may have a status and information, as well as messaging apps. Current approach is a pain for all the people who use autohiding dock. I would be glad if this coul be reopened.
