### ISSUE TITLE
Feature request: use Apple's in built emoji

### ISSUE THREAD

**Issue by nzjoel** [rsms/fb-mac-messenger#206]
I would like to use the standard emoji from Mac OS and iOS instead of the really big Facebook ones. There doesn't seem to be a way of using them other than to select one in another app like the default Messages app, copy, paste it into the text and then send.

**Comment by tarikd** [comment]
CMD + CTRL + SPACE

**Comment by nzjoel** [comment]
That's a good work around thanks! Would be nice to have an icon for it too, but may not be easy or worthwhile I guess.

**Comment by rsms** [comment]
wontfix
Aim of project is not to redefine the Messenger experience but to bring it to the desktop.
