### ISSUE TITLE
BUG: Can't move the application window

### ISSUE THREAD

**Issue by iamhenry** [rsms/fb-mac-messenger#207]
When I try to drag the window it doesn't move. Might be an issue with El Capitan.

**Comment by grodowski** [comment]
+1, also happens for me on El Capitan

**Comment by wojtczal** [comment]
+1

**Comment by ErikGartner** [comment]
+1

**Comment by joshvickerson** [comment]
I am usually able to move the window when I launch the application, but if I choose "Reload App From Server" then I'm not able to move the window. Relaunching the application _usually_ fixes it, but not always.

This is also on El Capitan

**Comment by minheq** [comment]
I work around this by dragging it when the windows is out of focus

**Comment by mik115** [comment]
+1

**Comment by joshvickerson** [comment]
@minheq Brilliant. Seems like the issue only occurs when the window has focus.

**Comment by RaphyRaph** [comment]
+1

**Comment by schrackin** [comment]
+1

**Comment by iamhenry** [comment]
Can't move window even out of focus.

**Comment by JoelOtter** [comment]
+1 - also can't move window when out of focus. El Capitan.

**Comment by rsms** [comment]
And this is using the latest version 0.1.5 published on 2015-09-18?
(I'm on 10.11 and am able to move the window of release 0.1.5)

**Comment by rsms** [comment]
Please provide exact OS version (apple menu > about, click on version, post version and build)

**Comment by JoelOtter** [comment]
OS X: 10.11.1 (15B42)
Messenger: 0.1.4 - I'll try an update.

**Update**: Working fine now. Thanks. :)

**Comment by rsms** [comment]
In the future, please make sure you're either using a build from latest master source or the most recent release when submitting an issue.
