### ISSUE TITLE
Glitches when typing in Vietnamese

### ISSUE THREAD

**Issue by lvnguyen** [rsms/fb-mac-messenger#208]
It seems that Messenger gets occasional glitches when I type in Vietnamese (using standard Telex package from OS X). Glitches include:
- Unable to hit delete button
- Hitting double enter to send a message
- Text that I deleted mysteriously reappear when submitting
- Some words that I type get consistently "corrected", even though they are correct in vocabulary.

Reproduction will be posted if requested, although it seems to only hit occasionally.

**Comment by rsms** [comment]
Does this work in Safari? (messenger.com)
