### ISSUE TITLE
Glitch: Exit, Minimize, and Fullscreen buttons lose positioning

### ISSUE THREAD

**Issue by joshmelikian** [rsms/fb-mac-messenger#209]
<img width="318" alt="screen shot 2015-10-10 at 12 31 43 pm" src="https://cloud.githubusercontent.com/assets/6232105/10412431/3d3f13c4-6f4b-11e5-85a8-e75fbe423f1a.png">

After returning to the standard window from fullscreen in El Capitan, the buttons lose their placement. They're still usable, but only a small portion of them are visible.

**Comment by joshvickerson** [comment]
Resizing the window after returning from fullscreen fixes their positioning. Seems like just a miscalculation in positioning when the window sizes back down from fullscreen.

**Comment by bradreardon** [comment]
Duplicate of #194
