### ISSUE TITLE
Bug with Japanese Romaji Input

### ISSUE THREAD

**Issue by milso** [rsms/fb-mac-messenger#210]
I use Japanese keyboard input with Romaji input mode in place of an English keyboard layout and found a small bug. The first character typed always duplicates itself, for instance typing "Hello" or "goodbye" would actually produce "HHello" or "ggoodbye" respectively in the message box. Switching to an English keyboard layout has been a workaround but also a slight nuisance.

**Comment by rsms** [comment]
Does this work in Safari (messenger.com)?

**Comment by simonyangme** [comment]
This works fine in Safari. Looks like a bug with the app.

I've checked using the following: Version 0.1.7 and Safari 9.0.3 (11601.4.4), both running on 10.11.3 (15D21)
