### ISSUE TITLE
Coloring is getting messed up, possibly only with stickers (screenshot included)

### ISSUE THREAD

**Issue by joshwertheim** [rsms/fb-mac-messenger#211]
Tends to be cyan or similar. Occasionally edges are reddish. Happens in the client, but not at messenger.com from the browser. Usually it's only stickers with color issues, but occasionally the entire background has this issue too.

![screenshot](http://i.imgur.com/HF2qdmC.png)

**Comment by joshvickerson** [comment]
This is happening to me with all images that I receive or send. Example:
![screen shot 2015-10-15 at 11 53 00 am](https://cloud.githubusercontent.com/assets/2325487/10519376/69549416-7333-11e5-9d7c-6ff95e3aae94.png)

The images appear fine on messenger.com and within messenger on Facebook, just appear discolored like this in the app.

**Comment by cwRichardKim** [comment]
Yea, I believe this is a known el capitan issue (happens on youtube too)

**Comment by elijahcarrel** [comment]
For what it's worth, mine are always pink! All images I send and receive, not just stickers.
![screenshot 2016-01-30 23 28 33](https://cloud.githubusercontent.com/assets/6487982/12700249/9eb2d5c6-c7a9-11e5-808e-ec05af697654.png)

**Comment by mporcheron** [comment]
Are people using f.lux? There seems to have been problems with Intel Iris Graphics, El Capitan and f.lux for some time?

**Comment by elijahcarrel** [comment]
Yes, I'm using f.lux. However, I have a MacBook Air with Intel HD Graphics 6000, not Intel Iris. I've never experienced any problems until this.

**Comment by joshwertheim** [comment]
@mporcheron I haven't been using f.lux for this issue, though it hasn't happened much lately.

**Comment by rsms** [comment]
wontfix nonapp

**Comment by joshwertheim** [comment]
@rsms is there a clear cause for this outside of the app?

**Comment by rsms** [comment]
@joshwertheim I've got five macbooks all running different hardware and OS X versions, and I can't seem to repro this. On this computer (MacBook 12" retina) OS X 10.11.3 with latest Flux, I do get some weird stuff like this in iTunes playing videos sometimes (known Flux issue) but not with Messenger. So it's really hard to tell where the issue lies. Until someone has a clear description of the circumstances (i.e. can explain how this app can be changed to remedy the issue) I'll keep this issue closed.

**Comment by joshwertheim** [comment]
@rsms, odd; I've never come across it outside the messenger app. I'll try to reproduce it again manually, if possible. If I can do that then I'll send info your way.

Thanks for looking into it, though!

**Comment by rsms** [comment]
Perhaps there's a certain type of image (e.g. encoded with a certain PNG encoder, only JPEGs, etc) that triggers the issue.
