### ISSUE TITLE
Main window not movable at all in El Capitan

### ISSUE THREAD

**Issue by robco** [rsms/fb-mac-messenger#212]
Steps to reproduce:
1. Open FB messenger app
2. Try to move window with mouse
=> Window not movable at all, works fine in Yosemite

**Comment by joshvickerson** [comment]
Duplicate of #207.

**Comment by CristianMoisei** [comment]
+1 for this.

**Comment by schrackin** [comment]
+1

**Comment by framerate** [comment]
Use the developer version listed in the readme. @schrackin @CristianMoisei  @joshvickerson @robco

**Comment by ghost** [comment]
+1

**Comment by joshvickerson** [comment]
@framerate the issue appears to be fixed in the developer version.

**Comment by joevo2** [comment]
+1

**Comment by rsms** [comment]
dupe
