### ISSUE TITLE
Not possible to send photo in El Capitan

### ISSUE THREAD

**Issue by robco** [rsms/fb-mac-messenger#215]
Steps to reproduce:
1. Launch FB messenger app
2. Open conversation
3. Drag and drop photo to the conversation window
   => nothing happens (EXPECTED: photo is sent to the recipient)
4. Choose in menu to attach photo
5. In photo attachment dialog choose photo to attach and confirm
   => Nothing happens (EXPECTED: photo is sent to the recipient)

**Comment by j6k4m8** [comment]
I found that pasting a photo from clipboard into the text box fails; pasting it when the _conversation window_ is focused (no blinking text cursor) seems to work. 

Wonder if this is related?

**Comment by rsms** [comment]
This should be handled by messenger.com
Closing this for now.
