### ISSUE TITLE
Ability to toggle "Message Requests" view

### ISSUE THREAD

**Issue by danshao** [rsms/fb-mac-messenger#216]
Is there any way to see "Other" messages through this app?

**Comment by rsms** [comment]
Note: Settings menu nowadays includes "Message Requests" — we should hook it up to a main menu item.

**Comment by rsms** [comment]
Fixed in [0.1.7](https://github.com/rsms/fb-mac-messenger/commit/87ab1525023bef4b9f451c66956e0bbf88dc8585)
