### ISSUE TITLE
Weird characters in message list

### ISSUE THREAD

**Issue by zulhfreelancer** [rsms/fb-mac-messenger#217]
Inside the message list, the message preview contains weird characters. But when I opened the full message, the message content rendered normally.

![screen shot 2015-10-30 at 10 08 22 am](https://cloud.githubusercontent.com/assets/3416976/10836911/6e5def5e-7eee-11e5-8b18-eca138cf010c.png)

I'm using the latest version `0.1.5`.

**Comment by rsms** [comment]
OS version?
App version?
OS language?
Does messenger.com render in the same way in Safari?
