### ISSUE TITLE
The new message button goes under three colored window button in narrow widths 

### ISSUE THREAD

**Issue by mohsen1** [rsms/fb-mac-messenger#219]
![screen shot 2015-11-02 at 3 15 58 pm](https://cloud.githubusercontent.com/assets/543633/10897305/c8cc3b7a-8174-11e5-81ad-38820b75679a.png)

**Comment by mohsen1** [comment]
Solution could be some overriding CSS that pushes down the top of the left column down a bit

**Comment by nzjoel** [comment]
Duplicate of the same bug I raised some time ago: 
https://github.com/rsms/fb-mac-messenger/issues/198

**Comment by rsms** [comment]
Fixed in 0.1.6
