### ISSUE TITLE
not able to sign out

### ISSUE THREAD

**Issue by 0BeaVer0** [rsms/fb-mac-messenger#220]
Is there a way to sign out?
When i click 'sign out' in the messenger menu, it doesn't do a thing.
I also tried uninstalling and reinstalling the app, but it keeps me logged in.

**Comment by rsms** [comment]
Not really, no. Forcing sign-out would require us to blow all facebook cookies, which includes Safari and other apps using webviews with the shared cookie storage. In the meantime, you can use Safari to sign out and it should be reflected in the app.

**Comment by rsms** [comment]
Fixed in 0.1.7
