### ISSUE TITLE
Jumping conversations with ⌘1..9 stopped working

### ISSUE THREAD

**Issue by mcescalante** [rsms/fb-mac-messenger#223]
In version 0.0.4, a feature was added:
- "Enabled jumping to a conversation using ⌘1..9 where the number correlates to the "nth" list item"

I dearly love this feature, but today there were definitely some changes shipped to Messenger that catches all ⌘1..9 presses and maps 1, 2, and 3 to info, smileys, and gifs. I'd love to be able to either toggle this somehow, or just get it set back so I can jump conversations instead of open smilies.

**Comment by narfdotpl** [comment]
I noticed it too and fixed it in #224.
