### ISSUE TITLE
Filtered Requests navigation is obscured by window controls

### ISSUE THREAD

**Issue by chrismessina** [rsms/fb-mac-messenger#226]
Take a look:

<img width="384" alt="screenshot_11_18_15__7_52_pm" src="https://cloud.githubusercontent.com/assets/22610/11261935/3e15b3fa-8e2e-11e5-9bb4-df7df025899d.png">

It should be possible to hit the "back" arrow...

**Comment by davepagurek** [comment]
I added a stylesheet that gets injected in https://github.com/rsms/fb-mac-messenger/pull/222, I can add a rule in there. Do you know if there's a way to force this view to show up for testing purposes without having actually received a message request that gets filtered?

**Comment by chrismessina** [comment]
@davepagurek oh man, not sure. All my requests went away. You could try to message me and then I might see your request: facebook.com/chrismessina

**Comment by rsms** [comment]
Interesting. I wonder if there's a way to either:
a. Detect this state and hide the window controls until state is existed, or
b. Manipulate the DOM for this state to move the chevron to the RHS of the zoom window button, which is kind of what #222 does

**Comment by chrismessina** [comment]
Yeah, the #222 solution seems apropos. Still trying to reproduce the
appearance of this menu!

**Comment by chrismessina** [comment]
Ok, got one...!

![screenshot_1_10_16__6_07_pm](https://cloud.githubusercontent.com/assets/22610/12225698/0546a3c0-b7c5-11e5-8811-975da3ba8012.png)

When I go back, the gear is stuck under the window buttons:

![screenshot_1_10_16__6_08_pm](https://cloud.githubusercontent.com/assets/22610/12225703/1d34e69a-b7c5-11e5-96d9-3ca31dac718a.png)

**Comment by rsms** [comment]
Would be happy to accept a patch for this

**Comment by rsms** [comment]
https://github.com/rsms/fb-mac-messenger/compare/ee5f7c8c5e94cb3069d1610edc2093903142b784...cdafa42ed45434b62c03d2af690aa5263feed120 should resolve this. Adds a View > Message Requests item to the main menu, hides window controls (in favor for the "back" chevron button) in message requests and filtered messages view,  and also correctly hides the gear icon again after navigating back to the "inbox."
