### ISSUE TITLE
"Select Conversation" options don't work

### ISSUE THREAD

**Issue by KinaKalamari** [rsms/fb-mac-messenger#229]
Cntrl+tab and contrl+shift+tab don't work, and the association commands in the "Window" menu do nothing when clicked. My workaround is to use the normal tab command to open the search bar and then arrow key down to the correct person, which is not all that helpful and it would probably be easier to just use the mouse at that point.

I'm running it on OSX 10.10.4, if that's relevant.

**Comment by rsms** [comment]
Try using option-arrow keys or cmd-1..9
