### ISSUE TITLE
Allow the main window to be a little narrower

### ISSUE THREAD

**Issue by jorisw** [rsms/fb-mac-messenger#230]
Call me a nitpick, but I am always a bit bothered when an app that I want to use casually in the background, takes up more screen real estate than it has to.

The main window now won't go smaller than 606px on my 1440px wide MacBook Air screen. I think it would do just fine at 400px wide. For reference, Apple's Messages.app goes as narrow as 480px.

**Comment by davepagurek** [comment]
I'm attempting to address this in https://github.com/rsms/fb-mac-messenger/pull/222

**Comment by rsms** [comment]
Fixed in 0.1.6

**Comment by jorisw** [comment]
👍 perfect.
