### ISSUE TITLE
Enable native messenger customization

### ISSUE THREAD

**Issue by josephmilla** [rsms/fb-mac-messenger#234]
Facebook messenger just released an update wherein you can customize the following:
- Nicknames
- Color
- Emoji

It would be nice to have these on the app as well

**Comment by joshvickerson** [comment]
This app is just a wrapper around the messenger.com web app. When Facebook adds these features to messenger.com they should come to the app (though you may need to reload from server a couple times).

Facebook usually rolls updates out over time. At the moment, I am not seeing these features on messenger.com though others may receive them at different times.
