### ISSUE TITLE
Add support for using Ctrl+Tab or Ctrl+Shift+Tab to switch between conversations

### ISSUE THREAD

**Issue by zicvic** [rsms/fb-mac-messenger#235]
Using Ctrl and Ctrl+Shift as modifiers to Tab does not invoke the known behaviour from the native Messages app where you jump between conversations just as in Safari.

**Comment by mcescalante** [comment]
If you hold `option` and use the up and down arrow keys on your keyboard, you can switch between conversations that way. Just a quick workaround I've been using since the ⌘1..9 stopped working :)

**Comment by rsms** [comment]
opt-arrows is what Facebook thinks is best. The goal of this project is to put messenger.com on the desktop, not to reinvent it.
