### ISSUE TITLE
CAN YOU INTEGRATE FB MESSAGING INTO OSX MESSAGES?

### ISSUE THREAD

**Issue by ghost** [rsms/fb-mac-messenger#236]
Hi,

I've just discovered that FB is pulling Jabber usage so I can no longer use the FB account on OSX Messages. Instead of a separate app, is there a way to instead make an add-on that works in Messages, to bring logging into an account again? That would be so useful.

I hope you find a solution and stop this FB stupidity of taking out basic functionality from apps.

Thanks!

**Comment by mcescalante** [comment]
I do not think that this is aim of this project. This is a standalone native client for messenger.com, not an add-on for Apple's Messages

**Comment by ghost** [comment]
Coolio. I must say it is much better than the Jabber equivalent in Messages. But if someone chooses to make a plug-in for Messages, that would be terrific. :)

**Comment by rsms** [comment]
invalid
