### ISSUE TITLE
Window buttons bug

### ISSUE THREAD

**Issue by panr** [rsms/fb-mac-messenger#24]
![window_buttons](https://cloud.githubusercontent.com/assets/1303365/7064651/a7ac7dea-deb0-11e4-9fe5-77d3d0d784b8.png)

When you hover the cursor on the window bar to interact with the app window, buttons appear on the settings icon...

**Comment by iamgp** [comment]
This is a feature (#12)

**Comment by shaishav** [comment]
I still don't understand why hiding title bar + traffic light buttons is necessary, IMO it looks better with visible title-bar.
![title-bar](http://i.imgur.com/Jn3hgRe.jpg)

fullscreen mode still works perfectly fine and the title bar will disappear, so I don't see a problem. (#12)

**Comment by rsms** [comment]
This is a matter of opinion. We, the authors, believe that you spend relatively little time interacting with the window itself (moving it) so we optimize for clarity of content and a clean view. This is why the "stop lights" hide automatically while the pointer is outside of the window's titlebar.

**Comment by panr** [comment]
To be clear, auto-hide feature is okay. "Stop lights" position is buggy for me - too close to the settings icon...
