### ISSUE TITLE
Regarding App Appearance and Custom CSS

### ISSUE THREAD

**Issue by cooperpellaton** [rsms/fb-mac-messenger#242]
Because of the way that this is written with the webView not being able to `drawBackground` I cannot just hard code a different set of environment variables to set the background color to black. 

Do you believe it would be best to on-load pass in a custom CSS file to the webview so that the proper appearance can be loaded or would you prefer that I fork and/or make a pull request for a different schema by which the appearance can be changed?

For reference, I tried this and it did not work.

```
NSFileManager *fileManager = [NSFileManager defaultManager];
WebPreferences *webPrefs = [WebPreferences standardPreferences];
[webPrefs setUserStyleSheetEnabled:YES];
NSString *folder = @"~/Users/cooperpellaton/Documents/Projects/fb-mac-messenger/fb-mac-messenger/Messenger/";
folder = [folder stringByExpandingTildeInPath];

if ([fileManager fileExistsAtPath:folder] == NO) {
        [fileManager createDirectoryAtPath:folder withIntermediateDirectories:YES attributes:nil error:NULL];
    }
NSURL *fileURL = [NSURL fileURLWithPath:@"/Users/cooperpellaton/Documents/Projects/fb-mac-messenger/fb-mac-messenger/Messenger/fb-messenger-dark.css"];
[webPrefs setUserStyleSheetLocation:fileURL];
[webView setPreferences:webPrefs];
```

**Comment by rsms** [comment]
wontfix
