### ISSUE TITLE
Remote Login/Forum Question

### ISSUE THREAD

**Issue by tikilab** [rsms/fb-mac-messenger#243]
Is there a forum where I can ask questions about this app? I have a potential issue but it may be completely unrelated and I need help from someone who knows the code. Namely, an "Android" phone supposedly logged into my Facebook account from California yesterday as I was using this app. I've taken the appropriate steps to change my password, etc, but I would like to know if this app logs in remotely in any way, like on a virtual server or whatever, or if the IP address should be from where I live (i.e. not California).

I'm sorry to misuse this space. I'll delete this issue as soon as I get an answer. Otherwise consider "the app doesn't have a forum" to be my issue and delete/proceed accordingly.

**Comment by rsms** [comment]
I'm afraid not. Best place to ask about 99% of this app is to ask Facebook Inc via customer support. You can also try https://www.facebook.com/help/735006619902401
