### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by Kajvdh** [rsms/fb-mac-messenger#245]
There are 65 open issues and the last commit lasts from 4 months ago

**Comment by ashokfernandez** [comment]
Was just about to come here to ask the same thing. Huge amount of PRs too that have been left hanging.

**Comment by rsms** [comment]
Not dead, I'm just a regular guy who has a daytime job. Don't expect _me_ to implement and fix all kinds of crazy requests. This is just a place for _us_ to discuss what to change.

Is there something in the app you want to change? Fix it and send a PR explaining why everyone else should have it too.

**Comment by bradreardon** [comment]
@rsms not particularly suggesting myself since I have extremely limited Objective C experience, but it may be good to add some more maintainers to the project if you see it fit. This is definitely a project I'd like to see actively maintained since Messenger is a commonly used app of mine.

**Comment by rsms** [comment]
http://fbmacmessenger.rsms.me/ 0.1.6 released
