### ISSUE TITLE
Vulnerable Sparke version

### ISSUE THREAD

**Issue by grEvenX** [rsms/fb-mac-messenger#248]
Sparkle framework should be updated to 1.13.1 to avoid MItM attacks, see https://vulnsec.com/2016/osx-apps-vulnerabilities/

**Comment by rsms** [comment]
Oh, thanks for noticing. I'll update Sparkle right away when I get home tonight, and will push out a new build.

**Comment by rsms** [comment]
I wonder if we could use https://raw.githubusercontent.com/rsms/fb-mac-messenger/master/website/changelog.xml instead of http://fbmacmessenger.rsms.me/changelog.xml to address the TLS issue.

**Comment by rsms** [comment]
Note: There will be no security patch release as Messenger isn't critically vulnerable. The only way someone could successfully Man-in-the-middle attack a Messenger installation is by having my Apple Developer certificate for this app. Sparkle asks OS X to check the signature of the apps (vA vs vB) when verifying a new version. The next release of Messenger will ship with Sparkle 1.13.1.

**Comment by rsms** [comment]
Related task: #250
