### ISSUE TITLE
Menubar icon (Status item)

### ISSUE THREAD

**Issue by patricks** [rsms/fb-mac-messenger#25]
Hi,

I really like this app, only if it available for a few days/hours. It does would it should. 
But I have two feature requests:
- Menubar-Icon
- New message badge on the app icon

**Comment by ericluii** [comment]
New message badge on app icon in PR: #28

**Comment by rsms** [comment]
#28 has landed, so unseen badging is done.
Whenever I hear someone asking for a status item in the system menu bar an alarm bell goes off in my mind — _why_ should Messenger have a status item? To show unseen count? In that case, isn't the two existing areas (dock and cmd-tab switcher) enough?

**Comment by iamgp** [comment]
I guess unless you want _neither_ the dock nor the cmd-tab switcher, and just a status item…

**Comment by rsms** [comment]
@iamgp True. Though that would be pretty far away from OS X standards (i.e. interactive apps reside in the dock, while status items in the status bar.)

**Comment by markesaaremets** [comment]
Behaviour of Current.app or Fantastical.app is great imo. You can choose to have a dock icon or not.

**Comment by leonardofaria** [comment]
Is it menu bar item available in the current version? I am not sure because I didn't find any option to show the app in the menu bar

**Comment by rsms** [comment]
Not doing a status item
