### ISSUE TITLE
[enhancement] "Seen icon" doesn't show time

### ISSUE THREAD

**Issue by patriciocordova** [rsms/fb-mac-messenger#253]
When I send a message and the other person sees it, a mini profile picture of the person appears next to the message indicating that they already saw it. If I hover (or click) on the person's mini profile picture I should be able to see the time that person saw the message.

It's a nice to have.

**Comment by rsms** [comment]
Not a feature of messenger.com
This project aims to put Messenger on the desktop, not reinvent it.

**Comment by patriciocordova** [comment]
"Reinvent" means start again something from scratch ;), this is actually a feature of the regular Facebook messenger.
