### ISSUE TITLE
Disabling sounds and notifications does not persist between app launches

### ISSUE THREAD

**Issue by ggutenberg** [rsms/fb-mac-messenger#254]
I launch the app.  I go to Preferences.  I uncheck Sounds (so that it says "Off" with no checkbox), and I click the Notifications text so that it says "Turn on desktop notifications".  I then click Done, and close the app.  Upon re-launching, _sometimes_ Sounds is checked again and says "On", and _always_ the Notifications text is back to "Turn off desktop notifications" (and have been re-enabled).

This is really annoying, as I don't want any sounds or notifications, so I have to manually disable these every time I launch the app.  Using v. 0.16.1455039740

**Comment by rsms** [comment]
Expected behavior. It's a bug with the WebView component used by this app on OS X 10.11. localStorage doesn't persist.
