### ISSUE TITLE
Preferences Menu Not Functional

### ISSUE THREAD

**Issue by darleenjg** [rsms/fb-mac-messenger#255]
Hello.  When I try to open the Preferences menu using Messenger > Preferences or ⌘, nothing happens.    The Preferences menu does not open.  I am using Messenger version 0.1.4 on a Mac OS 10.9.5

**Comment by rsms** [comment]
That's an old version which isn't supported anymore. I'd recommend upgrading to OS X 10.11 and use the most recent release.
