### ISSUE TITLE
Text input above the last message

### ISSUE THREAD

**Issue by tchiss** [rsms/fb-mac-messenger#259]
Hello,
On the newest version (0.1.7), the text input is above the last message.

https://s3-eu-west-1.amazonaws.com/tchissmedia/screenshot.png

I'm on El Capitan OSX 

kind regards.

**Comment by rsms** [comment]
Try the following things:
- Resized the window
- Reloaded the app (cmd-r)
- Restarted the app

If you're still having issues, let me know.
Can't reproduce this myself on the two computers I just tried it on.

**Comment by tchiss** [comment]
Well I resized the window, then that works. I reloaded the app, it works too. But when I restarted the app, I have the same issues, so I had to resize it again.
