### ISSUE TITLE
two factor auth support

### ISSUE THREAD

**Issue by odiak** [rsms/fb-mac-messenger#27]
I could not logged in Facebook on this app because (maybe) I enabled 2 factor auth.
![screen shot 2015-04-09 at 22 47 12](https://cloud.githubusercontent.com/assets/251857/7068001/66f33f5a-df0a-11e4-873f-fd9c729492d1.png)

After I entered email and password, error message (image above) was shown.
I clicked the link and signed in on browser but nothing happened.

Is there any way to log in?
Or please support logging in with 2FA.

**Comment by joshvickerson** [comment]
If you "Continue to Facebook" and approve the login and elect to "save the browser", then restart the messenger app and sign in again it should let you in okay (you may need to do that a couple times). It's rough but you'll get in.

2FA support would be very welcome, though.

**Comment by odiak** [comment]
I've gotten in. Thanks
