### ISSUE TITLE
Does not work with OS X 10.11.4 Beta 6

### ISSUE THREAD

**Issue by ghost** [rsms/fb-mac-messenger#273]
I just see an empty window and it crashes if I do some things in the menus.

![screen shot 2016-03-11 at 17 23 28](https://cloud.githubusercontent.com/assets/13749545/13708303/15eded14-e7ae-11e5-9090-4906cd7c0d49.png)

![screen shot 2016-03-11 at 17 25 26](https://cloud.githubusercontent.com/assets/13749545/13708332/4cc988d4-e7ae-11e5-95a3-0bfc6f3e923c.png)

**Comment by sammarcus** [comment]
@JulieBurke did this work on 10.11.3 for you? can you share the messages in your console? curious if they are similar to either #262 or #261, this looks similar.

**Comment by ghost** [comment]
Sorry, the first time I installed it I was already on 10.11.4 Beta 5 or 6.

I will have a look at the console later. I'll have to sleep now.

If it is using Safari it might be caused by uBlock or Ghostery.

Kind regards
Julie

**Comment by ghost** [comment]
Have the same issue with OSX 10.11.3 on fresh install.
Doing File -> Reload App From Server fixes it for me.
Program did crash the first time I did that though, it worked the second time.

**Comment by andreasmpet** [comment]
Same problem. 
OSX 10.11.3 with fresh install.
Safari Version  9.0.3

**Comment by md3kung** [comment]
I also have that same problem on OSX 10.11.3

**Comment by ghost** [comment]
Still not fixed.

**Comment by sammarcus** [comment]
Please post your logs. I believe this is the same issue as #262 and #261 so as many technical details as you can share would be especially helpful in organizing these issues and avoiding unnecessary duplicates.

**Comment by JulieBurke** [comment]
Sorry I don't have the Messenger anymore, but I could look if the console goes back 10-12 days.

**Comment by ghost** [comment]
I Just installed it again and it's the same. What log do you exactly mean?

`21/03/16 21:12:52,883 syspolicyd[1906]: assessment granted for .app by Developer ID
com.apple.message.domain: com.apple.security.assessment.outcome2
com.apple.message.signature2: bundle:me.rsms.fbmessenger
com.apple.message.signature3: .app
com.apple.message.signature5: 0.1.7
com.apple.message.signature: granted:Developer ID
com.apple.message.signature4: 1
SenderMachUUID: xxx
`

`21/03/16 21:13:54,076 loginwindow[93]: com.apple.message.domain: com.apple.BezelServices.IdleTimer
com.apple.message.result: pass
SenderMachUUID: xxx`

**Comment by sammarcus** [comment]
@JulieBurke those aren't related to this application. Try opening Console.app and filter for `messenger` in the search bar.

**Comment by Reidsy** [comment]
I get the following error in console.app when trying to start messenger (filtering on `messenger` and the process id)

```
3/21/16 10:33:31.647 PM Messenger[2388]: You must specify the URL of the appcast as the SUFeedURL key in either the Info.plist or the user defaults!
```

The app then sits with an empty progress bar.

If I reload the app (command-r) I get the following:

```
3/21/16 10:35:41.816 PM Messenger[2388]: tcp_connection_destination_perform_socket_connect 3 connectx to 2a03:2880:f00b:8:face:b00c::1.443@0 failed: [65] No route to host
3/21/16 10:38:01.000 PM kernel[0]: process Messenger[2388] thread 496585 caught burning CPU! It used more than 50% CPU (Actual recent usage: 99%) over 180 seconds. thread lifetime cpu usage 140.047433 seconds, (136.251596 user, 3.795837 system) ledger info: balance: 90004277911 credit: 139979958476 debit: 49975680565 limit: 90000000000 (50%) period: 180000000000 time since last refill (ns): 90414239355 
3/21/16 10:38:01.760 PM ReportCrash[2559]: Invoking spindump for pid=2388 thread=496585 percent_cpu=99 duration=91 because of excessive cpu utilization
3/21/16 10:38:13.034 PM com.apple.xpc.launchd[1]: (me.rsms.fbmessenger.115232[2388]) Service exited due to signal: Terminated: 15

```

The progress bar will fill up and the app will stop responding.

**Comment by quanglam2807** [comment]
It still doesn't work with the latest build of OSX 10.11.4.

**Comment by ghost** [comment]
Please fix it. It is the only Messenger app I use because it allows me to zoom texts inside of app.

**Comment by joshvickerson** [comment]
@Reidsy: no route to host error... Can you get to messenger.com in Safari? Just a wild guess here but could it be a DNS cache issue?

**Comment by Reidsy** [comment]
@joshvickerson I can access messenger.com from safari

The address points to an ipv6 address, I'm on an ipv4 network so the `no route to host` error makes sense.
The issue is occurring on a new install of messenger.
I have an existing install of messenger on another laptop running the same OS and revision of messenger, and it raises the same `no route to host` error in console.app, but does not have any issues starting up. I'm assuming it tries the ipv6 address and falls back to ipv4 if ipv6 fails.

**Comment by Reidsy** [comment]
I added the `SUFeedURL` to info.plist and it fixed the issue for me

https://gist.github.com/Reidsy/c851e756cf23f4819f61

I'll open up a PR

**Comment by ghost** [comment]
@Reidsy That worked. Thank you!

**Comment by lunks** [comment]
Using @Reidsy's patch fixed it for me as well.

**Comment by sammarcus** [comment]
#275 fixed it for me! great catch, thanks @Reidsy! will close #262.

**Comment by rsms** [comment]
@Reidsy When you got `You must specify the URL of the appcast as the SUFeedURL key in either the Info.plist or the user defaults!`, were you building your own version of Sparkle or were you using the latest release build of Messenger.app? I can't reproduce this and am running 10.11.4.

**Comment by Reidsy** [comment]
@rsms this is present in the latest build of Messenger.app
The reason it doesn't appear for users that have previously used the application is because that value has been saved in user defaults.
I have been able to reproduce this by adding and removing the key from `~/Library/Preferences/me.rsms.fbmessenger.plist

**Comment by rsms** [comment]
@Reidsy Interesting. I'll investigate. It's still really strange as the app doesn't use SUFeedURL (but sets the feedURL property of SUUpdater at launch; see AppDelegate.mm)

**Comment by Reidsy** [comment]
Yea this is an interesting issue, I'm guessing that sparkle is requesting the `SUFeedURL` key before it is being set in code (before `applicationDidFinishLaunching()`).
Just saw you removed the URL set in code. :+1:

**Comment by rsms** [comment]
@Reidsy Breaking in lldb, [SUUpdater sharedUpdater] called a method that faulted when there was no feedURL set. This is most likely a bug/oversight in the current version of Sparkle (how else would you ever _set_ feedURL on the shared SUUpdater object? :smile_cat:)
