### ISSUE TITLE
Possible malware infection.

### ISSUE THREAD

**Issue by ghost** [rsms/fb-mac-messenger#277]
Hello, Today I opened the messenger and this appered
<img width="754" alt="screen shot 2016-03-31 at 14 04 37" src="https://cloud.githubusercontent.com/assets/9155072/14175173/9eda5630-f749-11e5-88ce-83992a89054a.png">

So I continued, but then this appeared: 
<img width="756" alt="screen shot 2016-03-31 at 14 04 45" src="https://cloud.githubusercontent.com/assets/9155072/14175178/aa7cfb32-f749-11e5-944b-30fc469c12cd.png"> 

When I try to login to chrome and safari facebook doesn't show me this message. Is it safe to use messenger anymore? 

P.S I ran Malwarebytes and Avast and they didn't find anything harmful.

**Comment by unclejustin** [comment]
Just did a fresh install, no problem for me. This is almost definitely just on your local system.

**Comment by rsms** [comment]
This app is a web app — it simply wraps messenger.com using a WebView, which is a system component that shares plugins, cookies and other state with Safari (and any other app using WebViews with default cookie storage.) You most likely have something installed for WebKit (extension, plugin, etc) that Facebook sees as being malware.

What happened after you went through the Facebook malware helper? Were they able to provide you with information about what to do? If not, you should investigate further.

However, this is by 99.9999% certainty not related to this app, so closing this issue.

#invalid
