### ISSUE TITLE
Can't log into Messenger

### ISSUE THREAD

**Issue by jackiehluo** [rsms/fb-mac-messenger#278]
I just downloaded the app today, and the screen goes white after login. I tried reloading from the server a few times, which showed for a split second that I need to go to Facebook to continue login. Clicking the "continue" button doesn't go anywhere, and the screen goes white again before long. Everything, from moving the window to clicking the menu items, is super, super slow.

The only error I get in Console.app is that the process was caught burning CPU.

**Comment by chlab** [comment]
I also have this issue. Messenger used to work on my computer. Since I have a new MBP (running OS X 10.11.2) I cannot login. The progress bar loads, then the windows goes white and nothing happens.

**Comment by nclandrei** [comment]
Same issue here as well (OS X 10.11.4).

**Comment by atticoos** [comment]
Having this problem, here is a very detailed example :trollface: 

Might be worth noting i have 2FA enabled.

![screen shot 2016-06-20 at 2 48 17 pm](https://cloud.githubusercontent.com/assets/656630/16206362/14808c88-36f6-11e6-9e34-64f96d66b504.png)

**Comment by atticoos** [comment]
Ah, worth noting that I had to "allow this unrecognized device" to log in via the facebook web application.

**Comment by rsms** [comment]
#299 is a dupe but has more information and more conversation, so am closing this issue. Please refer to #299.
