### ISSUE TITLE
Blurry graphics

### ISSUE THREAD

**Issue by jlian** [rsms/fb-mac-messenger#279]
The icons are blurry compared to the website messenger.com on my rMBP. Is this a known issue? Is there a way to fix it?

This shows what I mean

http://imgur.com/a/Ycv43

First is from the app, the second one from the website.

**Comment by barvian** [comment]
I'm also having issues on a Retina Macbook Pro 15-inch (mid 2012). Love the app otherwise, though.

**Comment by rsms** [comment]
Not this app (issue with how messenger.com detects if it's rendering to a high-density display or not)
