### ISSUE TITLE
Unable to add emojis using the osx emojipopup

### ISSUE THREAD

**Issue by ssssamstrup** [rsms/fb-mac-messenger#287]
Pressing CTRL+CMD+SPACE brings up a popup where emojis can be added. When trying to do this in the app, the popup appears but when an emoji is chosen, it isn't written to the text-field (in some cases the emoji appears in the text-field for a moment, but then disappears again the next).

Screen-recording of issue: https://dl.dropboxusercontent.com/u/478737/Messengerformac-emojipop.mov

**Comment by joshvickerson** [comment]
Duplicate of #238.

**Comment by mariusfanu** [comment]
I have the same issue.

**Comment by blazeworx** [comment]
+1 Also happening for me.

**Comment by Allariah** [comment]
Still occurring as of 
Sierra: 10.12.1, Messenger 0.1.10

**Comment by rsms** [comment]
dupe of #238
