### ISSUE TITLE
App doesn't support 2 steps login

### ISSUE THREAD

**Issue by tkhieu** [rsms/fb-mac-messenger#290]
Hi team
My facebook account is set up 2 step verification to log in. And when I tried on `Messenger` app. It doesn't work. It displays a white page and when I reload the page, It asks me to click `Continue` and it will display a white page again.

**Comment by joshvickerson** [comment]
I ran into this issue as well. After making a few attempts through the app I managed to stumble my way through it to log in.

It's definitely an issue, but if you just keep trying long enough you'll get in - at least, I could :)

Edit: On Facebook.com I had a notification that an attempt to log in from a new browser was made. I indicated to Facebook that it was me, and told it to save the browser, then it worked.

**Comment by Otann** [comment]
I have the same problem, but when I refresh the with `⌘R` it asks me to complete sign in on Facebook and `Continue` button is not clickable:

![screen shot 2016-05-11 at 11 05 05](https://cloud.githubusercontent.com/assets/683786/15175803/5e18df60-1768-11e6-98b6-05795802ac84.png)

**Comment by owlboy** [comment]
I also had this issue.

Confirming the login was me on Facebook, and choosing to save the browser indeed worked.

The other thing I would note is when it is stuck in this issue, with a blank white screen, it also makes the whole app super unresponsive. Dragging the window and opening and selecting menus is heavily delayed, like the app is stuck in a furious loop of some sort.
