### ISSUE TITLE
Application crashes after failed login.

### ISSUE THREAD

**Issue by shahzeb1** [rsms/fb-mac-messenger#292]
App version: 0.1.7
Mac OSX: 10.10.5

Messenger applications opens, and if I enter in an incorrect email address & password combination, then it just hangs.

**Comment by markhughes** [comment]
I can confirm this is happening for me too on OSX 10.11.4

**Comment by sahil2441** [comment]
+1 for 10.11.4

**Comment by eddie-wang** [comment]
+1 for 10.11.4

**Comment by shahzeb1** [comment]
To fix, please update to the current version of fb-mac-messenger.
