### ISSUE TITLE
What is being done to keep my password safe?

### ISSUE THREAD

**Issue by juil** [rsms/fb-mac-messenger#294]
I'm not quite comfortable imputing my password into third party applications. Is there a reason why login doesn't redirect the user to an official Facebook authorization page like other web logins?

**Comment by ghost** [comment]
Facebook itself is doing "something" to keep your password safe. This app is only a wrapper around the web version (a web view). If this app was a Messenger _client_ (which Facebook usually -if not always- restricts, unlike Twitter) it would have an auth page, redirection, et al.

In short, you submit your password to Facebook servers.

![screenshot 2016-05-11 17 27 39](https://cloud.githubusercontent.com/assets/2186401/15198703/b5a34f5a-179e-11e6-98f2-da6284f6efb8.png)

**Comment by rsms** [comment]
This article should get you started https://www.facebook.com/help/213481848684090
