### ISSUE TITLE
"Change Emoji" box empty.

### ISSUE THREAD

**Issue by joelworsham** [rsms/fb-mac-messenger#297]
Running latest version - 0.1.7.1459534376
https://i.imgur.com/Cy9xKkD.png

**Comment by daviesgeek** [comment]
Works perfectly for me (0.1.9):

![image](https://cloud.githubusercontent.com/assets/2348508/19985485/2072d970-a1d0-11e6-9a84-0e0d9eda07b9.png)

**Comment by joelworsham** [comment]
Yup, it's working now!
