### ISSUE TITLE
Image upload button broken

### ISSUE THREAD

**Issue by tedlee** [rsms/fb-mac-messenger#3]
Expected behaviour is the standard upload dialog to pop-up. Seems to be broken in the current version.

![screen shot 2015-04-08 at 3 14 51 pm](https://cloud.githubusercontent.com/assets/465289/7056607/13c4cf50-de02-11e4-97d0-85cd2a31ce8f.png)

**Comment by rsms** [comment]
This is a known bug (actually, we have not yet implemented this)

**Comment by vikmeup** [comment]
@tedlee @rsms implemented. Please accept pull request: https://github.com/rsms/fb-mac-messenger/pull/17

**Comment by rsms** [comment]
Closed by 213b0619aa614e2c6e477117c6cec399e7b4af91

**Comment by tedlee** [comment]
@rsms awesome thanks! :thumbsup:
