### ISSUE TITLE
10.9

### ISSUE THREAD

**Issue by keehun** [rsms/fb-mac-messenger#30]
Why does it require 10.10? Could small changes be made to support 10.9?

**Comment by Risengan** [comment]
![capture d ecran 2015-04-10 a 03 00 37](https://cloud.githubusercontent.com/assets/11879201/7080151/d04ad300-df2d-11e4-9701-9369114859eb.png)
Surely for a next update ;)

**Comment by Risengan** [comment]
@rsms I sent you a mail :)
