### ISSUE TITLE
Window Buttons Obfuscated

### ISSUE THREAD

**Issue by psstmatt** [rsms/fb-mac-messenger#31]
![screenshot of button obfuscation](https://s3.amazonaws.com/f.cl.ly/items/3g0C2H1h371c1t3g443A/messenger-issue.png)
The close, minimize and zoom buttons are obfuscated by the settings gear.

**Comment by rsms** [comment]
dupe and not a bug

**Comment by panr** [comment]
@rsms ಠ_ಠ
