### ISSUE TITLE
When trying to play media via Touch Bar, OS alerts with ping sound

### ISSUE THREAD

**Issue by amja** [rsms/fb-mac-messenger#337]
On the Touch Bar of the new MacBook Pro, there is a UI element to pause/play and scrub any media playing in the various apps you have open. Without any video/audio playing in fb messenger, the scrubber appeared. When I pressed play, the messenger notification ping played. 

Maybe this is an implementation issue with the notification sound (the computer thinks it is a user-controllable piece of audio).

**Comment by rsms** [comment]
This is most likely an issue with messenger.com (the web app) and not this app (which is a wrapper for the web app.)

I don't have a new MBP, so can't fix this or ever try it.

**Comment by jrtc27** [comment]
This happens on messenger.com itself (and is extremely annoying).

**Comment by rsms** [comment]
Seems like an issue w/ messenger.com and not this app. Closing for now. Let's see if it's still an issue after the Messenger team has updated the app.

**Comment by MPV** [comment]
A similar thing happens when you have a video in a messenger conversation: the messenger app steals the native play/pause buttons on the Mac keyboard (from e.g. Spotify and/or other player) and use them for playing/pausing the video in the messenger app instead.
