### ISSUE TITLE
Eating a lot of RAM

### ISSUE THREAD

**Issue by emilstahl** [rsms/fb-mac-messenger#356]
1 GB+ RAM usage is quite high.. anyone else experiencing this?
![screen shot 2017-02-06 at 15 29 32](https://cloud.githubusercontent.com/assets/3885790/22650870/3c081b2c-ec81-11e6-9cac-e037829694a4.png)

**Comment by greiss122** [comment]
+1, seeing this too. Also the app doesn't use dynamic graphics switching so it's making me use the power-hungry Discrete graphics card! (info on that fix here: https://developer.apple.com/library/content/qa/qa1734/_index.html)

**Comment by rsms** [comment]
This is simply a fact of life nowadays with "web apps". Just look at your Slack app (which is like Messenger a web wrapper) — it uses 1.9GB.

Since this really has nothing to do with this app, but rather how Facebook built messenger.com and how Apple built WebKit, I'm closing this.

**Comment by rsms** [comment]
FYI version 0.1.11 uses very little memory on my machine
<img width="727" alt="screenshot 2017-02-11 13 57 52" src="https://cloud.githubusercontent.com/assets/47046/22857846/b3b3d884-f062-11e6-9bb1-32756bbbad06.png">
