### ISSUE TITLE
Messenger using Discrete dedicated graphics card instead of integrated or dynamic switching

### ISSUE THREAD

**Issue by greiss122** [rsms/fb-mac-messenger#357]
On my Macbook Pro 2016, somehow Messenger is the only app holding me back from using the Integrated graphics-- even Chrome has dynamic switching! This uses a TON of extra unnecessary power: quitting messenger brings my battery life estimate up 2 hours (!!!).

Info on how to fix this is here: https://developer.apple.com/library/content/qa/qa1734/_index.html
Thanks!

**Comment by rsms** [comment]
dupe #346
