### ISSUE TITLE
Suggestion: Ability to Mute/Delete/Leave Chats

### ISSUE THREAD

**Issue by minhoolee** [rsms/fb-mac-messenger#36]
Original Facebook messages has the ability to select a dropdown menu, in the chat settings, that allows the user to mute/delete/leave chats. This would need to stop desktop notifications as well.

**Comment by dapetcu21** [comment]
You can already do that:
![screen shot 2015-04-10 at 12 36 22](https://cloud.githubusercontent.com/assets/428060/7085309/3b2f3b02-df7e-11e4-8ecd-43caa5ca0a2d.png)

**Comment by minhoolee** [comment]
Sorry for the confusion, I meant mute the chat as in the entire conversation. Also, that dropdown menu does not show up for me? Are we talking about the messenger app from this repos?

![screen shot 2015-04-10 at 6 40 07 am](https://cloud.githubusercontent.com/assets/10465228/7088900/88fb1bd0-df4c-11e4-8a7f-b41b2905aa59.png)

**Comment by szhu** [comment]
> Sorry for the confusion, I meant mute the chat as in the entire conversation.

The "Mute" option does exactly that. dapetcu21's screenshot above was of an entire conversation, not a single message. ~~Also, what does it mean to mute a single message?~~

> Also, that dropdown menu does not show up for me?

In the conversation list on the left, hover over the conversation you want to mute. Then a "…" menu button will show up. Click it and you'll find the options above.

![screen recording 2015-04-10 at 01 29 pm](https://cloud.githubusercontent.com/assets/1570168/7096872/dbaf6e24-df85-11e4-8d4b-c9be8377e403.gif)

> Are we talking about the messenger app from this repos?

Yes

---

Just to be absolutely clear:

![screen recording 2015-04-10 at 01 37 pm](https://cloud.githubusercontent.com/assets/1570168/7097008/d0e0aa20-df86-11e4-8324-430404e60d99.gif)

**Comment by minhoolee** [comment]
Ah perfect, my bad.

**Comment by szhu** [comment]
No worries! Also, no need to edit the title – if the issue is closed, that means it's resolved.
