### ISSUE TITLE
DELETE THIS

### ISSUE THREAD

**Issue by jakezhuyi** [rsms/fb-mac-messenger#375]
The sign out on Mac OS is not working. 
![screen shot 2017-03-26 at 10 09 02](https://cloud.githubusercontent.com/assets/12618851/24331965/4a38a60c-120c-11e7-8957-033e71505d12.png)
When I hit Sign Out, it does absolutely nothing...

**Comment by rsms** [comment]
Does it work if you

1. View > Open Messenger Menu
2. click "Sign out"

?

**Comment by hampustagerud** [comment]
Using the latest code, it's working using either "Sign out..." or Messenger menu so maybe it's fixed?

**Comment by OSSYULYYZ** [comment]
Please delete this issue
