### ISSUE TITLE
Drag to attach file

### ISSUE THREAD

**Issue by oskarhane** [rsms/fb-mac-messenger#38]
I really miss the ability to drag a file to the input area to attach it. 
I use feature this a lot in Goofy, the client I currently use.

**Comment by dapetcu21** [comment]
+1. I'll slack off the whole Easter, so maybe I'll do a PR for this.

**Comment by tajo** [comment]
+1 I really like how iMessage handles this. Anyway, great job!

**Comment by homoky** [comment]
+1

**Comment by Risengan** [comment]
+1

**Comment by rsms** [comment]
Would be great. Best would be if Messenger.com implemented this, so we don't have to write some serious hacks (which we would need to.) Talking to the Facebook engineer behind Messenger.com it seems they have a lot of more things they want to do with messenger.com, so I'm hoping we'll see this feature soon :)

**Comment by peterjosling** [comment]
"Serious hacks" is basically a single line. The Messenger.com team are slacking 😉
