### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by TechGizmo** [rsms/fb-mac-messenger#380]
Im running messenger 0.1.13.1491443794 on OS X 10.11.2 El Capitan.

1) Notifications that are read are not removed from notification centre. It just stays there.

2) When opening the app for the first time, there will be a settings icon that is at the same position as the 3 dots. To remove it, I have to go to messenger > preferences. However, once I close the app and reopen, the same issue occurs.

3) It will also be nice if the messenger app has a sound control to overwrite the sound settings in System Preferences > Notifications "Play sound for notifications"

4) Notification banner does not show if my window is focused on someone while another person sends me a message. Occurs occasionally.

5) When gif is sent, battery usage increases significantly and remains high until the gif is out of view in the conversation.

6) When messages are read on another device (eg. phone), the app does not update in the background and the badge app icon is not updated (to not show red circle).

**Comment by chrismessina** [comment]
I'm seeing the same button-gear overlap:

![messenger_for_mac](https://cloud.githubusercontent.com/assets/22610/24841732/70efc738-1d3f-11e7-92d8-264dd086c869.png)

**Comment by rsms** [comment]
Thanks for the list, but it's impossible to track as "a grab bag of stuff" — could you please file as separate issues (and please please, search for existing issues, closed and open, before filing)
