### ISSUE TITLE
Home & End keys to navigate in text input

### ISSUE THREAD

**Issue by ww7** [rsms/fb-mac-messenger#383]
Not find shortcut for go Home and End in massages, only PgUp and PgDn works
It's limitation of Facebook API?

**Comment by rsms** [comment]
I don't own any keyboards with home and end keys, so I have no way to test this. Does it work for you in Safari?

25+ years of mac standard is cmd-uparrow and cmd-downarrow to jump to beginning and end of text.

**Comment by ww7** [comment]
cmd-uparrow and cmd-downarrow don't work too
