### ISSUE TITLE
"Connection is offline" on app startup

### ISSUE THREAD

**Issue by VirrageS** [rsms/fb-mac-messenger#384]
I am constantly getting this message at messenger startup:
![screen shot 2017-04-12 at 21 22 59](https://cloud.githubusercontent.com/assets/3855799/24975512/3cc93f6e-1fc6-11e7-9f98-24c5b9dafcac.png)

 I have tried to change networks and reload the app (`CMD + R`).

I am using 10.12.4 OS X. Is there something what could be a problem?

**Comment by TGNYC** [comment]
Perhaps your firewall blocks Messenger or Facebook (either or). I get that message when I edit the hosts file of my computer to block Facebook via [Self Control](https://selfcontrolapp.com/). You can test this by pinging messenger.com via Terminal.app.

**Comment by VirrageS** [comment]
You are right. I had Facebook blocked. I thought it only connects with Messenger. Thanks!
