### ISSUE TITLE
Question: why am I in India?

### ISSUE THREAD

**Issue by eexit** [rsms/fb-mac-messenger#39]
Hello,

First, thank you for working on this, this was verrrry expected!

I have a remark to make: once logged in, Facebook identifies the connection from Chennai, India (5.175.83.20).
Any reason for this? It doesn't feel safe.

Thanks,

**Comment by rsms** [comment]
You're probably connected to a VPN. This has nothing to do with this app. If this is a real concern, you should contact Facebook and I'm sure they'll help you resolve any security concerns. A simple way to feel safe is to change your Facebook password (and be sure to enable two-factor authentication.)
