### ISSUE TITLE
After hibernate/sleep Messenger sometimes no longer works properly. Red 'Messenger is currently unavailable' error

### ISSUE THREAD

**Issue by russelltrafford** [rsms/fb-mac-messenger#390]
After my Mac is sent to sleep by closing the screen lid at the end of the day, when I come back in the morning and log back in, opening Messenger presents me with an error message as shown below.

<img width="421" alt="screen shot 2017-04-21 at 7 29 50 am" src="https://cloud.githubusercontent.com/assets/22302818/25440164/6cfc8adc-2a53-11e7-91f4-c8f88796aafa.png">

The app does not function correctly once this message is shown, and is essentially unusable. The only solution to fix this is to close the Messenger down completely, and then re-start it again.

I have seen this issue come up many times, across all the recent versions, but had not thought to file a bug till now.

I believe it might have to do with the Macbook maybe going to sleep/hibernating? Maybe that means there is no polling to the application to keep the session going? Does it time out maybe?

If thats the case, and its unavoidable, maybe an app-reload option perhaps, or a better error message which does not appear in the top square of the app, almost unreadable. Im assuming this is an uncaught error message, as it would not be designed to go into that small space by default.

Anyway, hope thats enough info, if you need more, feel free to ask me.

**Comment by rsms** [comment]
What leads you to believe that it's a bug in this app? It's just a webview that loads messenger.com

If there's something specific pointing to the app (not messenger.com), let me know and I'll reopen this issue.

**Comment by russelltrafford** [comment]
I see what you mean, yeah maybe the web version of the application is not designed to survive a suspended state from sleep/hibernate. I'll test on the webapp, and see if it happens there too then.

**Comment by ekumanov** [comment]
I have this problem too. Isn't there a way for the app to detect laptop is being awoken and then forcefully reset/refresh the webview or whatever it is? It's sometime very frustrating to open my laptop and keep doing my work thinking messenger is working while it fact it it isn't and thus I miss messages.
