### ISSUE TITLE
Feature/debug request: Debug mode to access the JS Console output to help with bug reports

### ISSUE THREAD

**Issue by russelltrafford** [rsms/fb-mac-messenger#391]
As a side note, I assume this is some kind of webview app, as it uses the web version of messenger, so is there a way you can have a debug button/setting where we can open up the javascript console? That way we can relay any error messages found back to you.

**Comment by rsms** [comment]
Hold opt key and right-click — you should get the option to "inspect element" to bring up the dev tools.

**Comment by russelltrafford** [comment]
@rsms that does not seem to do anything for me. Tried both left and right option keys.
