### ISSUE TITLE
Make entire header bar area "grabbable" to move the window

### ISSUE THREAD

**Issue by cowboy** [rsms/fb-mac-messenger#40]
The window seems to be draggable if clicked in the top ~20px of the header bar, but it would be nice if you could click to drag _anywhere_ in the header bar. Ie. everything above the horizontal grey line (well, except for the blue buttons)

**Comment by dinhvh** [comment]
+1

**Comment by rsms** [comment]
Would be nice. Probably an easy hack to do.

**Comment by dapetcu21** [comment]
If this gets implemented, moving the 3 rainbow buttons a bit out of the way of the gear icon would also be welcomed
