### ISSUE TITLE
Blank screen with error "Could not display conversation list."

### ISSUE THREAD

**Issue by ginomempin** [rsms/fb-mac-messenger#404]
As stated in the title, when I open the app, it just displays the following screen:

![screen shot 2017-07-15 at 11 44 30 am](https://user-images.githubusercontent.com/6091865/28235902-4ce5f7f8-6953-11e7-9809-bb3e0fc1734b.png)

The screen is blank.
All I can see is the error "Could not display conversation list." on the top left and the name of my most recent conversation.

I've already tried/checked the following:
1. My internet connection is OK
1. When I use the official Messenger web client or the mobile app, I can access my conversations OK.
1. Tried signing-out of the app but the **Messenger** > **Sign-out...** does not do anything
    * The **View** > **Open Messenger Menu** also does not work
1. **Messenger** > **Reload app from server**
1. Uninstalled then re-installed the app
1. Cleared app caches (using CCleaner)
    * This forced the app to sign-out, but the issue persisted when I signed back in.
1. Restarted my Mac (a couple of times)

I'm using:
* Mac OS X 10.10.5
* Messenger-0.1.13.1491443794-7b1777b58fef0bf9

As far as I can remember, I'm sure it was still working on 3 days ago (Wed, 07/12)

**Comment by pilagod** [comment]
Same problem here ! I'm using OSX 10.11.6, and I have no idea about what happens 😢

**Comment by wamos** [comment]
In the web version, the rightmost column displays "shared files". Maybe the api has updated a bit.

**Comment by ginomempin** [comment]
The app's working normally again.  
I think we can close this issue now.

**Comment by zawhpone** [comment]
Me have same problem
![Screenshot_2020-12-19-14-05-38](https://user-images.githubusercontent.com/76243115/102688941-cc618400-4228-11eb-917e-c7a0cb083106.jpeg)

**Comment by zawhpone** [comment]
Anyone can help me i report tenical error but it's still not working.
