### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by jklausa** [rsms/fb-mac-messenger#41]
Hey,

I hate the way helvetica neue looks on messenger and I'd love to have some kind of custom CSS injection capabilities (or just a preference somewhere to change it to San Francisco). I know this is kind of a weird feature to have, so I'm willing to implement it myself, if anyone can point me where I should start, because I have no idea where should I hook in to do that.

**Comment by rsms** [comment]
You'll want to look at `webView:didClearWindowObject:forFrame:` which is called when the view's JS context has been setup (but most likely before the HTML DOM exists.) Execute some JS to add your CSS.

I just tried this and it works pretty well:

``` mm
[webView.mainFrame.windowObject evaluateWebScript:
 @"document.addEventListener('DOMContentLoaded', function() { var s = document.createElement('style'); s.innerText = '* { font-family:\"marker felt\"; }'; document.head.appendChild(s); console.log('done'); });"];
```

![screenshot 2015-04-10 18 56 12](https://cloud.githubusercontent.com/assets/47046/7099791/6c64a02e-dfb3-11e4-959d-ce8e9a7447d1.png)

I don't think we should add this to the main release, but making your own build is pretty easy :)
