### ISSUE TITLE
'Presentation Mode' no longer supported?

### ISSUE THREAD

**Issue by ccunniff** [rsms/fb-mac-messenger#43]
I just upgraded to the newest build 0.0.4.

Is there a reason for removing Presentation Mode? The presentation mode button was replaced with just a maximize button.

![screen shot 2015-04-10 at 11 41 56 am](https://cloud.githubusercontent.com/assets/1513329/7091332/fb339d88-df76-11e4-9c52-f7b5e66488cd.png)

-Chris

**Comment by nostalgiaz** [comment]
+1
