### ISSUE TITLE
Broken on macOS 10.4 Mojave

### ISSUE THREAD

**Issue by gandalfsaxe** [rsms/fb-mac-messenger#436]
Sidebar is blank, main content window is blank, but top bar showing which contact is selected is the only thing showing. See screenshot below:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/12127864/41022451-f12b0fbc-6969-11e8-8daa-eff19d768d9a.png">

**Comment by puhtaytow** [comment]
After recompilation under xcode10, it's black.

You could glitch it by clicking video conference button and then switch between tabs by command + digit

**Comment by puhtaytow** [comment]
Messenger[5005:145277] ADD: failed to create cache dictionary at path=/Users/xxx/Library/Caches/me.rsms.fbmessenger.

This is the only error I have got from the debugger. Also, looks like it can write inside (deleted cache files appearing after next start) and even with 777 error still exist. My OS is out of jail.

**Comment by puhtaytow** [comment]
Problem doesn't exist on Developer Preview Beta 2.

**Comment by gandalfsaxe** [comment]
Indeed, it's fixed with beta 2 👍
