### ISSUE TITLE
Issues logging in with 2-factor authentication

### ISSUE THREAD

**Issue by AbirRazzak** [rsms/fb-mac-messenger#437]
[Screen when logging in](https://gyazo.com/3ccc6b6529f48df40609c7f9735f8800)
[What messenger app looks like after verifying 2-factor log-in](https://gyazo.com/c690fc64efacbf10f98e0512e58812b1)

I recently added 2-factor authentication to my facebook account and now messenger app isn't working for me. When I click continue it redirects me to my default browser (firefox) and I'm already logged in. Copied the link and opened it up in Safari, set up the facebook account in safari, and still the same problem, it's asking me to verify still. The screen goes blank after doing anything.

**Comment by simplenotezy** [comment]
I believe I have the same issue.

![image](https://user-images.githubusercontent.com/3786627/45025139-fdf3b880-b03a-11e8-886e-3460d3937a9d.png)

**Comment by AbirRazzak** [comment]
It went away from me, I'm not quite sure what did it though..

**Comment by simplenotezy** [comment]
I used Goofy - I find it works better. Dunnno the differences though. http://www.goofyapp.com/
