### ISSUE TITLE
Message typing box broken after Dragging file onto window. 10.10

### ISSUE THREAD

**Issue by rizenfrmtheashes** [rsms/fb-mac-messenger#47]
Whenever you type a message and send it, 

![screen shot 2015-04-10 at 12 43 42 pm](https://cloud.githubusercontent.com/assets/2954959/7095466/8d0618a0-df7f-11e4-92b5-44fda3f8c9a5.png)

and then drag a file into the chat box (like  a photo and this doesn't work) and then try to type another message, 

![screen shot 2015-04-10 at 12 44 18 pm](https://cloud.githubusercontent.com/assets/2954959/7095469/90b0f39e-df7f-11e4-84b5-8cc241fdff0d.png)

it doesn't recognize  a message is being typed. Pressing enter just expands the text box, does not send the message. 

![screen shot 2015-04-10 at 12 46 30 pm](https://cloud.githubusercontent.com/assets/2954959/7095477/a0d4abe4-df7f-11e4-8589-768b6880bdc6.png)

**Comment by rizenfrmtheashes** [comment]
This may also coincide with a feature request to allow files to be drag/dropped into the chatbox to attach them.  adding this feature may solve this bug.

**Comment by rizenfrmtheashes** [comment]
This also scrolls the entire interface down and causes the top settings/ui bar to disappear. This is when you repeatedly "enter" during the bugged chatbox. . 
![screen shot 2015-04-10 at 12 49 17 pm](https://cloud.githubusercontent.com/assets/2954959/7095637/c972aac8-df80-11e4-9695-d58813700a73.png)

**Comment by rsms** [comment]
After restarting the app (and thus reloading messenger.com), does it work?

This is an issue with messenger.com and not this app. #wontfix
