### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by dominikwilkowski** [rsms/fb-mac-messenger#5]
Hey there,

great idea. I had facebook connected in my messenger app but it doesn't support group messages so this is great. The only thing I would love to have is system notifications.

Cheers

**Comment by laander** [comment]
+1 for this, including perhaps a menu bar icon so the app itself can be closed from the dock

**Comment by rsms** [comment]
Done in v0.0.2.
Resolved by 42b6eabd3a3f5fcc236b49be377426d25e2c2e65

**Comment by dominikwilkowski** [comment]
:+1: Great! I just downloaded it and built it! works great.
