### ISSUE TITLE
It doesn't work on my macbook

### ISSUE THREAD

**Issue by amewayne** [rsms/fb-mac-messenger#63]
System ver: OS X 10.10.3，i put it into my Application directory, but when i opened it, it didn't show anything on the window.

**Comment by anatolinicolae** [comment]
OS X 10.10.3 here, but it works fine for me!

**Comment by dhalima3** [comment]
Yea same here!  Works fine on OS X 10.10.3 for me.  Have you tried re-downloading the application again?

**Comment by rsms** [comment]
invalid

**Comment by rsms** [comment]
Related: Show "mom proof" loading/progress UI when loading messenger.com, useful for slow connections where the window will just be white until UI has started.

**Comment by amewayne** [comment]
Oh snap. It looks like your connection is offline, please try again later.

**Comment by tillkrueger** [comment]
^ did you ever find out what caused the "Oh snap. It looks like your connection is offline, please try again later." message, hqweiyu ?
