### ISSUE TITLE
Truncated contacts sidebar

### ISSUE THREAD

**Issue by asherism** [rsms/fb-mac-messenger#67]
![screen shot 2015-04-13 at 9 50 06 pm](https://cloud.githubusercontent.com/assets/11524787/7128353/742b0cd2-e227-11e4-9338-12b236d698e0.png)

Goofy's feature, might be a nice enhancement?

**Comment by rsms** [comment]
This project aims to bring Messenger to the desktop, not reinvent it or derive from it. I believe in the Facebook Messenger team and for them to make sensible UI decisions — if messenger.com adds this feature we will see it here, if not: not.

**Comment by asherism** [comment]
Totally.
