### ISSUE TITLE
settings cog location

### ISSUE THREAD

**Issue by leslie-w** [rsms/fb-mac-messenger#68]
Hey guys,

Great tool, its super useful for me, allowing me to chat with a sleek imessage-esque look without the distractions of the fb timeline/notifications. 

One thing is the placement of the settings gear and the apple minimize/full screen buttons. It would be great if you could move it slightly so people can avoid accidentally hitting the wrong thing.

keep it up. If it helps Im running OSX10.10.3 (14D131)

![screen shot 2015-04-13 at 10 30 13 pm](https://cloud.githubusercontent.com/assets/6618975/7129304/acb9b47c-e22c-11e4-94c5-1219a7954106.png)

**Comment by asherism** [comment]
already fixed in 74a33ccf728756c48246b89236f145a8d63de1b0

**Comment by leslie-w** [comment]
awesome! sorry, my version says i'm up to date, havent tried the latest build yet.

**Comment by asherism** [comment]
my bad, @leslie-w! wasn't aware that the latest build hasn't been pushed yet.
