### ISSUE TITLE
Mac "Alert" sound played after chat select

### ISSUE THREAD

**Issue by ronaldho** [rsms/fb-mac-messenger#69]
Hello. 

I found a small annoyance that occurs after selecting a chat and the user begins typing. I believe, because the left pane is not a text field, Mac issues the "alert" sound, before the window switches to the text field. Note that, the input IS captured, but the sound is still played.

This also happens sometimes when I CMD-Tab back to the Messenger window, but the below steps are the one of the reliable ways to reproduce the problem.

Steps to reproduce:
1. Select a new chat on the left side panel with your mouse
2. Begin typing (without explicitly clicking the text field)
3. OS X makes the "Alert" sound as defined under System Preferences > Sound > Sound Effects

Expected results:
OS X should not play the "Alert" sound

**Comment by rsms** [comment]
duplicate

**Comment by ronaldho** [comment]
Apologies @rsms , should have looked at the closed issues
