### ISSUE TITLE
Turn the whole message thread into a click-area for input focus

### ISSUE THREAD

**Issue by tosh** [rsms/fb-mac-messenger#70]
The better chat clients out there behave in a way where a click somewhere onto the message thread will focus the input so you can easily add a reply (most likely the primary action apart from reading/scrolling).

http://en.wikipedia.org/wiki/Fitts%27s_law

**Comment by asherism** [comment]
Why the whole message thread? Is the input area not enough?

**Comment by tosh** [comment]
The larger the click-area is the easier it is to perform the action. If you've tried chat clients that support this behaviour it is frustrating to go back to ones that don't.

An even better behaviour could be to just allow typing at any time whether the input field is focused or not. This might make some potential keyboard combinations impossible but imho the use-case of writing a reply is so fundamental to chat that it is worth the trade-off.

**Comment by asherism** [comment]
I think that goes beyond the scope of this project. The aim is to provide Messenger on desktop, not to reinvent, or derive from it. I do see merit in your suggestions, but it will probably be up to the Messenger team to provide such functionalities.
