### ISSUE TITLE
UI problem with preferences

### ISSUE THREAD

**Issue by greenchapter** [rsms/fb-mac-messenger#71]
In the 0.0.5 Version you have a little UI Problem on the left-top-corner. At current state of the app, you can't click the preferences icon.

![bildschirmfoto 2015-04-14 um 12 56 43](https://cloud.githubusercontent.com/assets/693276/7135933/e0568420-e2ab-11e4-88ef-7b2553ab54ef.png)

**Comment by mojo2012** [comment]
and the preference menu entry from the main menu doesn't work either

**Comment by cvx** [comment]
Some of the features are currently incompatible with non-English Messenger interface.

**Comment by mattbroussard** [comment]
With my language set to English, I have this problem also.
