### ISSUE TITLE
Zoom in/out keybinds (⌘+/⌘-) don't work.

### ISSUE THREAD

**Issue by cowboy** [rsms/fb-mac-messenger#73]
Pressing **⌘+** and **⌘-** don't do anything here, although choosing Zoom In and Zoom Out from the View menu work just fine. Pressing **⌘0** to reset to 100% does work, however.

I'm in an almost completely stock OS X 10.10.3, in case that helps.

**Comment by mcescalante** [comment]
I also have this behavior, but I am running OSX `10.9.5`. I made sure to shut off my OSX system zoom modifiers before testing (thought that could be an issue at first). I hardly use the zoom, but wanted to chime in to say that I noticed this behavior (in 0.0.4 too).

**Comment by rsms** [comment]
What system locale and what keyboard hardware?

**Comment by rsms** [comment]
Found the issue. 64cf745d4a9e9b1bf5d1095944141cb27e4a0a59 (PR #29) introduced cmd-1..9 to jump to conversations, but incorrectly assumed ANSI 1..9 key codes are sequential (which they are not, which is a whole different story.) Basically the "if" branch is incorrectly taken for cmd+ and cmd-. I've got a patch for it I'll land after work tonight.

**Comment by mcescalante** [comment]
Awesome @rsms sorry I wasn't able to get back to you in time with more info - that is a very reasonable reason why it would be not working. Thank you for catching the source of the issue and for this wonderful software!
