### ISSUE TITLE
Titlebar not correctly shown in full screen mode

### ISSUE THREAD

**Issue by mojo2012** [rsms/fb-mac-messenger#74]
When maximized the title bar is partially hidden under the menubar. This makes unmaximize pretty hard.

![bildschirmfoto 2015-04-14 um 16 12 22](https://cloud.githubusercontent.com/assets/1330361/7138519/29a730d8-e2c1-11e4-9972-c6c643660231.png)

**Comment by abhiklodh** [comment]
Same here

**Comment by Risengan** [comment]
Same :/

**Comment by mattbroussard** [comment]
Same.

**Comment by rsms** [comment]
Changes requested to #84

**Comment by rsms** [comment]
Fixed by b6270d973e13163a8dcf4ec20c4fca34b063dd65 (@mattbroussard)
