### ISSUE TITLE
Location Of User When Chatting

### ISSUE THREAD

**Issue by abhiklodh** [rsms/fb-mac-messenger#75]
I can't see the location of my friend when he is chatting neither can i see my own location even if i am seeing older chats, this can been seen on The iOS Messenger App.
I know this is still a beta thing so i must not criticise, take ur time guys :) ...just letting u know the bugs(perhaps not,maybe features)
:+1:  If this gets covered ;P

**Comment by tmyrden** [comment]
This isn't exposed by messenger.com. Nothing this 3rd party app can do to add this feature. Would have to be added to messenger.com, in which case it would be reflected immediately in the app.
