### ISSUE TITLE
Cannot drag images from desktop to share within the conversation

### ISSUE THREAD

**Issue by johnpc** [rsms/fb-mac-messenger#77]
messenger.com features a button you can use to share files from your computer, or you can drag the image into the text box.

![screen shot 2015-04-14 at 3 23 13 pm](https://cloud.githubusercontent.com/assets/4824042/7145447/41d54f5c-e2ba-11e4-99e2-adc616957821.png)

In the app, this button is missing and dragging from the desktop doesn't work:

![screen shot 2015-04-14 at 3 24 14 pm](https://cloud.githubusercontent.com/assets/4824042/7145463/5234695a-e2ba-11e4-94eb-44947ca6f88d.png)

**Comment by rsms** [comment]
Can't reproduce. Messenger.com in Safari 8.0 only supports dropping a file onto the file icon, not the text box as you propose. This app adds additional code to allow dropping a file anywhere in the conversation, which works for me with the current release version of the app (0.0.5)

Please list all details of your software and step-by-step to repro.

**Comment by johnpc** [comment]
Ah, I opened up the wrong fb wrapper app. [This](http://www.goofyapp.com/) one has the error, yours is just a better app. :+1:
