### ISSUE TITLE
Use ctrl+tab to switch between conversations.

### ISSUE THREAD

**Issue by neerajbaid** [rsms/fb-mac-messenger#78]
Just like in native Messages.

I will poke around with this in a bit, just wanted to put the idea out there.

**Comment by ronaldho** [comment]
Also Cmd+ ] and Cmd + [ should map to moving between conversations too

**Comment by neerajbaid** [comment]
which of "[" and "]" is moving down and up?
edit: i'm guessing "[" is down and "]" is up

**Comment by neerajbaid** [comment]
Lol looks like this is being handled in #76.

**Comment by ronaldho** [comment]
@neerajbaid  well, if we're going with Messages convention, ] is down and [ is up actually (try it out)

but yes, looks like #76 is handling this

**Comment by neerajbaid** [comment]
@patrick-deutschmann

**Comment by rsms** [comment]
Protip: You can use Cmd-1..9 to jump to nth conversation.
We're still waiting for an update to #76 (or a different PR) to fix some issues with fragile JS.

**Comment by rsms** [comment]
See https://github.com/rsms/fb-mac-messenger/pull/76#issuecomment-109805155 for what's needed to get this going.

**Comment by dlitvakb** [comment]
@rsms I would suggest using also Cmd+Shift+Up/Cmd+Shift+Down or Cmd+Up/Cmd+Down for same purpose, many other messaging applications use that control scheme for moving across conversations (i.e. Adium, LimeChat)

**Comment by rsms** [comment]
Closed by #171
