### ISSUE TITLE
Settings "gear" icon is gone after 0.0.5 update

### ISSUE THREAD

**Issue by szhu** [rsms/fb-mac-messenger#79]
| 0.0.4 | 0.0.5 |
| --- | --- |
| ![screen shot 2015-04-14 at 3 17 52 pm](https://cloud.githubusercontent.com/assets/1570168/7148618/78b89afc-e2b9-11e4-9af4-831f630ae705.png) | ![screen shot 2015-04-14 at 3 18 09 pm](https://cloud.githubusercontent.com/assets/1570168/7148619/7b5083a6-e2b9-11e4-8115-b1c40b53614d.png) |

![out](https://cloud.githubusercontent.com/assets/1570168/7148629/97d76fb2-e2b9-11e4-9ddd-ea157c72581f.gif)

**Comment by szhu** [comment]
Wait, was this intentional?

**Comment by szhu** [comment]
Kinda weird but if I go to Messenger » Log out, it pops open the menu, without logging me out:

![screen shot 2015-04-14 at 3 20 39 pm](https://cloud.githubusercontent.com/assets/1570168/7148649/da2dfe94-e2b9-11e4-87cd-f93bacb4f222.png)

**Comment by szhu** [comment]
Messenger » Preferences prompts me to delete the conversation.

I think whatever scripting is being used to automate this is not reliable and should not be done.

**Comment by rsms** [comment]
Yeah, injecting JS is terrible. But it's what we are doing because apparently everyone seems to love that idea. About to land a diff that makes this better.

**Comment by szhu** [comment]
I think a reasonable thing to do is at least double check the name of the menu item before clicking on it. I've accidentally downloaded new stickers and deleted conversations by trying to get to preferences; please be safe rather than sorry.

Or at least bring the gear back, right now I have a problem that I can't even get to settings if I wanted to without potentially doing something bad.
