### ISSUE TITLE
Can't play voice memos

### ISSUE THREAD

**Issue by samuelcouch** [rsms/fb-mac-messenger#80]
When you receive voice messages, you can't play them within the app.

Running `0.0.6` on OSX `10.10.3`

Clicking on ► button does nothing.

**Comment by ritvik1512** [comment]
Exactly. I believe this has been pointed out before. I am working on it. I suppose I'll make a pull request soon. @rsms

**Comment by rsms** [comment]
Works for me. Just sent myself a voice memo and played it back in the app. When filing a bug, please provide complete details about all involved software, together with steps to reproduce.

**Comment by samuelcouch** [comment]
@rsms updated to add more context -- apologies for leaving out some information. As for reproducing, it simply doesn't work for me, new or old voice memos aren't playing when you click the ► button.
