### ISSUE TITLE
"Page not found"

### ISSUE THREAD

**Issue by lisovet** [rsms/fb-mac-messenger#81]
The app doesn't work/open at all. It says "Page not found", and the console shows:

`Failed to load resource: the server responded with a status of 404 (Not Found): https://www.messenger.com/t/`

**Comment by lisovet** [comment]
![screenshot_4_14_15__9_41_pm](https://cloud.githubusercontent.com/assets/6423183/7150861/15d1fbb4-e2ef-11e4-9fa7-8672ac5887b5.png)

**Comment by npgm** [comment]
Exact same issue. I deleted the app and redownloaded, still no fix.

**Comment by mcescalante** [comment]
Same issue for me, I also removed the entire thing with AppCleaner and re-downloaded, and opened. Just says "page not found."

**Comment by FrankWu100** [comment]
#83 can Fix this
