### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by lorinbute** [rsms/fb-mac-messenger#85]
Since today (15th of April 2015) whenever I open the app this is the only thing I see: Page not found. It's in the top left corner near the window buttons.

**Comment by bryangarza** [comment]
Here's a screenshot: 

![screenshot 2015-04-14 23 18 20](https://cloud.githubusercontent.com/assets/1396101/7153171/965ecac0-e2fc-11e4-8105-7d4f378e5657.png)

**Comment by sieumeo** [comment]
Second it. I've also tried reinstalling, logging out, reload from server to no avail.

**Comment by merlinND** [comment]
Same here :cry:

**Comment by cvx** [comment]
The fix is already on master (https://github.com/rsms/fb-mac-messenger/commit/07d3eb63382aafac5594dfc0616bc5aa41490715). I'm sure that 0.0.6 will be released shortly.

**Comment by merlinND** [comment]
That was fast :)

**Comment by rsms** [comment]
Closed by 07d3eb63382aafac5594dfc0616bc5aa41490715
