### ISSUE TITLE
First character system beep

### ISSUE THREAD

**Issue by samuelcouch** [rsms/fb-mac-messenger#9]
The first character typed in a message window results in the error sound.

**Comment by rsms** [comment]
Can't reproduce

**Comment by asherism** [comment]
Happens to me too...

**Comment by rsms** [comment]
Can you please list all steps and details required to reproduce this? ping @asherism @samuelcouch

**Comment by asherism** [comment]
It'll try my best! It just sort of happens on open. Nothing triggers it.

**Comment by rsms** [comment]
So you _don't_ press any key? I'm confused.

**Comment by joshpuckett** [comment]
@Jedmund was running in to this as well. Justin, can you post the video you sent me?

**Comment by asherism** [comment]
The sound only occurs on the first character of the first word.

**Comment by adi-dhulipala** [comment]
i've been experiencing this as well

**Comment by asherism** [comment]
https://dl.dropboxusercontent.com/u/77683401/alert.mov

**Comment by samuelcouch** [comment]
I've consistently had this happen every time:
1. Open Messenger (0.0.1 & 0.0.2)
2. Open any message or create a new message
3. Type in the `message` box (Doesn't occur in the `search` or `to` boxes)
   -----> The first character typed results in the error sound (As the video above shows)

For reference I'm on OSX 10.10.3

**Comment by rsms** [comment]
I can reproduce (also, my alert sounds were turned off in syspref)

This is really weird. Has anyone been able to debug this, or even get close? I've tried a couple of things, like providing various WebUIDelegate messages, but still getting this sound.

**Comment by nirav** [comment]
I've been working on this since yesterday and I can't figure out what the hell is going on.

**Comment by knowbody** [comment]
I've spent an hour and have no clue. thought it might've been something with `acceptsFirstResponder`. will give it ago in the morning once again, unless is solved

**Comment by rsms** [comment]
Truly a mystery!

**Comment by mynameisraj** [comment]
If it helps, I think this is because the `message` box is not an `input` but instead a `div` with `contenteditable` true. Looked at it myself but haven't figured it out yet… setting a `keydown` listener which blocks the event handler makes the sound go away. Something in WebKit, perhaps?

**Comment by rsms** [comment]
@mynameisraj Interesting. I wonder why it doesn't happen in Safari, which uses pretty much the same stuff as this app does.

**Comment by laserbeam** [comment]
Here the bug only appears if desktop notifications are turned on (in the messenger settings). If they are turned off there is no annoying sound.

**Comment by dapetcu21** [comment]
@laserbeam I can't confirm that on my box.

**Comment by igorcamilo** [comment]
Did you guys try it with WKWebView? Sorry, I'm very busy and can't test it myself right now. BTW, great work with this app!

**Comment by laserbeam** [comment]
Strangely enough, the sound doesn't trigger when you hit backspace and the field is empty. Maybe that was the original intention? And an if statement is just wrong?

**Comment by szhu** [comment]
btw I have seen this bug on both 10.9 and 10.10.

Here's an annotated recording of it happening:

![recording](https://cloud.githubusercontent.com/assets/1570168/7095672/15c3ddc0-df81-11e4-88eb-a2a6a9c6f75b.gif)

**Comment by szhu** [comment]
Also, can I suggest this issue be edited to include the phrase "system beep"? I believe that is the proper term for the sound. I originally couldn't find this issue through search because it was missing those terms.

**Comment by knowbody** [comment]
I created a separate project with the simplest possible webview and I get the same thing. Anyone tried to reimplement with WKWebView as @obitow suggested?

**Comment by rschmukler** [comment]
Can confirm this issue on `10.10.3`.

**Comment by nirav** [comment]
I tried using WKWebView, same issue exists there.

**Comment by matthewmueller** [comment]
Haha i thought i was going crazy. This is happening to me as well

**Comment by nirav** [comment]
So it looks like this guy fixed this issue and I am not quite sure how. 

http://www.producthunt.com/l/b222d33ef44ee0/1
Messenger for Desktop Beautiful Mac, Linux & Windows client for Facebook Messenger

**Comment by greenchapter** [comment]
This guy write the complete wrapper in node-webkit. I think this problem only exits on native apps. The guy from http://goofyapp.com had the same problem...
https://github.com/danielbuechele/goofy/issues/31

**Comment by asherism** [comment]
@greenchapter latest goofy app update fixes the issue somehow..

**Comment by blakeembrey** [comment]
I managed to patch this with the pointer that @asherism provided :smile: I've never played with Objective-C before so that was fun (yesterday was hours of googling why it was beeping and learning how to do symbolic breakpoints and so on).

**Comment by asherism** [comment]
@blakeembrey 🙏 🙏 🙏

**Comment by rsms** [comment]
@blakeembrey Nice work!

**Comment by dapetcu21** [comment]
This still happens with 0.0.6

**Comment by dapetcu21** [comment]
Nevermind, this was a result of #86

**Comment by firmread** [comment]
Just want to leave note here in case someone went through the same path with me. 
I was still getting the beep sound from version 0.0.6 when I first updated it from older version. 
A simple right click > Reload solved it for good. 

Thanks you all for this great app!

**Comment by lightheaded** [comment]
I still had the beep sound, but @firmread's suggestion worked like a charm. Thanks for dissolving my agony!

**Comment by cowboy** [comment]
FWIW, I had the beep sound in 0.0.7 but @firmread's suggestion helped.
