### ISSUE TITLE
"Application Not Responding" when a message is received

### ISSUE THREAD

**Issue by lisovet** [rsms/fb-mac-messenger#91]
Messenger freezes up when a message is received. It crashes, and the only way to get it working is to restart it. 

http://i.imgur.com/5KhCofT.png

**Comment by rsms** [comment]
Please provide detailed information about software, hardware and conditions, along with steps to reproduce, when filing an issue. There's nothing I can do about this.

**Comment by lisovet** [comment]
This issue seems to have resolved itself after a restart. It was occurring whenever a message was received. The only step to reproduce was to open Messenger, go into other applications, and receive a message while it was open. It would then freeze up/become unresponsive.

I was on an earlier version of Yosemite beta, so that may have contributed to the issue.

**Comment by rsms** [comment]
Weird. Yeah, perhaps the Webkit build on your machine was weirdo.
