### ISSUE TITLE
Suggestion: Esc to close conversation & Unread filter

### ISSUE THREAD

**Issue by zulhfreelancer** [rsms/fb-mac-messenger#92]
I would like to suggest 2 things:
1. Press Esc to close conversation like in Telegram for Mac client app
2. Add Unread messages filter in the messages list

Thanks.

**Comment by rsms** [comment]
What does "close" mean? What would happen when a conversation is closed? There's no way to "go".

When it comes to 2, you'll have to describe what you mean.
