### ISSUE TITLE
in full screen mode, the navigation items are partially hidden

### ISSUE THREAD

**Issue by TPei** [rsms/fb-mac-messenger#94]
![screen shot 2015-04-18 at 18 39 44](https://cloud.githubusercontent.com/assets/4004343/7216285/5097d242-e5fa-11e4-8efd-87784eedfb82.png)

**Comment by TPei** [comment]
that is, when hovering over that corner in order to show the menu / leave full screen mode

**Comment by rsms** [comment]
And you are using the latest version? (0.0.6)

**Comment by TPei** [comment]
yep, on 10.10.2

**Comment by joshwertheim** [comment]
Same here on 0.0.6 and using 10.10.3 (if that helps).

**Comment by rsms** [comment]
Help wanted as I can't reproduce this.

**Comment by rsms** [comment]
Hm, I think you may be using the 0.0.6 **release build** — I was assuming you were running a build from master. When filing issues, please make it clear exactly what version you're building from.

Try a build from source (or the just-published 0.0.7 build) and let us know if the issue persists.

**Comment by TPei** [comment]
works fine in the 0.0.7 build
