### ISSUE TITLE
Beep sound is back! on selected text regions.

### ISSUE THREAD

**Issue by laserbeam** [rsms/fb-mac-messenger#97]
Steps to reproduce:
1. Select a region of test (using shift, or dragging with the mouse).
2. Press any letter on the keyboard.

Effects:
The infamous system beep bug.

This happens even though #9 appears fixed here. Using 0.0.6 (latest release).

**Comment by mcescalante** [comment]
Yep, selecting the text does it for me. `⌘ + A` then a letter doesn't trigger it though.

**Comment by blakeembrey** [comment]
@laserbeam You're right. I based it on the first character, but when you select it in reverse it will have the opposite direction. Let me find a patch now :+1:
