### ISSUE TITLE
Notification Center image is too large

### ISSUE THREAD

**Issue by olivvybee** [rsms/fb-mac-messenger#98]
The profile picture image used in Notification Center seems much too big, in my opinion.

![screen shot 2015-04-20 at 21 49 21](https://cloud.githubusercontent.com/assets/661493/7240204/497e711a-e7a7-11e4-83bb-e6c82aebe00a.png)

**Comment by Lotuashvili** [comment]
Would be great smaller icon :)

**Comment by dapetcu21** [comment]
I never used the Notifications API, but I'm pretty sure that's not configurable.

**Comment by olivvybee** [comment]
@dapetcu21 The OS X [`NSUserNotification` API](https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSUserNotification_Class/#//apple_ref/occ/instp/NSUserNotification/contentImage) just takes an arbitrary `NSImage` as the icon to use, so a smaller image could just be passed in.

**Comment by dapetcu21** [comment]
Yeah, but then it would look bad when the notification would come up as a badge.

**Comment by dapetcu21** [comment]
Actually, let me try that

**Comment by rsms** [comment]
It's a hack to put the face of a person into the HUD notifications. Unfortunately a side effect of this is large "image attachments" in the notification center.

Options here are:
1. Remove profile picture from notifications
2. Keep it as-is
