### ISSUE TITLE
Settings icon overlapping with window controls

### ISSUE THREAD

**Issue by bernardorufino** [rsms/fb-mac-messenger#99]
![screen shot 2015-04-21 at 13 33 21](https://cloud.githubusercontent.com/assets/1025913/7257407/e372c71a-e82b-11e4-9b04-ec8e1573cb65.png)

**Comment by gabriellewee** [comment]
Don't know if this is related, but selecting Preferences from the menu now does nothing.

**Comment by orbxball** [comment]
same Problem Q___Q
And now the search bar is missing

**Comment by dapetcu21** [comment]
Fixed in #103, Duplicate #102, #101, #104

**Comment by greenchapter** [comment]
In version 0.0.9 the bug is almost there 
![bildschirmfoto 2015-06-17 um 22 17 22](https://cloud.githubusercontent.com/assets/693276/8217584/a5bf8878-153e-11e5-9a64-dc262a72bd6b.png)

**Comment by orbxball** [comment]
same problem@@ (Maybe its' because Facebook have change its API...
and another problem about the stickers. It cannot show
![2015-06-18 9 36 17](https://cloud.githubusercontent.com/assets/10207726/8222417/a8385bc0-159d-11e5-8314-31f280266de5.png)

**Comment by vmarks** [comment]
This behavior is back in 0.1.13
